-- phpMyAdmin SQL Dump
-- version 4.8.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 03, 2019 at 01:26 AM
-- Server version: 10.1.31-MariaDB
-- PHP Version: 7.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pencarian_data`
--

-- --------------------------------------------------------

--
-- Table structure for table `data`
--

CREATE TABLE `data` (
  `kode_barang` varchar(10) NOT NULL,
  `nama_barang` varchar(20) NOT NULL,
  `merek_barang` varchar(20) NOT NULL,
  `tgl_pengiriman` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `data`
--

INSERT INTO `data` (`kode_barang`, `nama_barang`, `merek_barang`, `tgl_pengiriman`) VALUES
('120', 'bagus', 'sabun', '0000-00-00'),
('121', 'ayu', 'shampoo', '2018-12-25');

-- --------------------------------------------------------

--
-- Table structure for table `hadits`
--

CREATE TABLE `hadits` (
  `id_hadits` int(11) NOT NULL,
  `jenis_hadits` text NOT NULL,
  `ayat` text NOT NULL,
  `artinya` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `hadits`
--

INSERT INTO `hadits` (`id_hadits`, `jenis_hadits`, `ayat`, `artinya`) VALUES
(49, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø¬ÙŽØ§Ø¨ÙØ±Ù Ø¨Ù’Ù†Ù Ø¹ÙŽØ¨Ù’Ø¯Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ù‚ÙŽØ§Ù„ÙŽ Ø´ÙŽÙ‡ÙØ¯Ù’ØªÙ Ù…ÙŽØ¹ÙŽ Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù -ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù…- Ø§Ù„Ø£ÙŽØ¶Ù’Ø­ÙŽÙ‰ Ø¨ÙØ§Ù„Ù’Ù…ÙØµÙŽÙ„Ù‘ÙŽÙ‰ ÙÙŽÙ„ÙŽÙ…Ù‘ÙŽØ§ Ù‚ÙŽØ¶ÙŽÙ‰ Ø®ÙØ·Ù’Ø¨ÙŽØªÙŽÙ‡Ù Ù†ÙŽØ²ÙŽÙ„ÙŽ Ù…ÙÙ†Ù’ Ù…ÙÙ†Ù’Ø¨ÙŽØ±ÙÙ‡Ù ÙˆÙŽØ£ÙØªÙÙ‰ÙŽ Ø¨ÙÙƒÙŽØ¨Ù’Ø´Ù ÙÙŽØ°ÙŽØ¨ÙŽØ­ÙŽÙ‡Ù Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù -ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù…- Ø¨ÙÙŠÙŽØ¯ÙÙ‡Ù ÙˆÙŽÙ‚ÙŽØ§Ù„ÙŽ: (( Ø¨ÙØ³Ù’Ù…Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù ÙˆÙŽØ§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø£ÙŽÙƒÙ’Ø¨ÙŽØ±Ù Ù‡ÙŽØ°ÙŽØ§ Ø¹ÙŽÙ†Ù‘ÙÙ‰ ÙˆÙŽØ¹ÙŽÙ…Ù‘ÙŽÙ†Ù’ Ù„ÙŽÙ…Ù’ ÙŠÙØ¶ÙŽØ­Ù‘Ù Ù…ÙÙ†Ù’ Ø£ÙÙ…Ù‘ÙŽØªÙÙ‰ )).', 'Artinya :Diriwayatkan dari Jabir bin â€˜AbdillahÂ radhiallahu â€˜anhuÂ bahwasanya dia berkata, â€œSaya menghadiri shalat idul-Adha bersama RasulullahÂ shallallahu â€˜alaihi wa sallamÂ di mushalla (tanah lapang). Setelah beliau berkhutbah, beliau turun dari mimbarnya dan didatangkan kepadanya seekor kambing. Kemudian RasulullahÂ shallallahu â€˜alaihi wa sallamÂ menyembelihnya dengan tangannya, sambil mengatakan:Â Dengan nama Allah. Allah Maha Besar. Kambing ini dariku dan dari orang-orang yang belum menyembelih di kalangan umatkuâ€'),
(50, 'Qurban', '( ÙƒÙÙ†ÙŽÙ‘Ø§ ÙˆÙÙ‚ÙÙˆÙÙ‹Ø§ Ù…ÙŽØ¹ÙŽ Ø§Ù„Ù†ÙŽÙ‘Ø¨ÙÙ‰ÙÙ‘ Â ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… Ø¨ÙØ¹ÙŽØ±ÙŽÙÙŽØ§ØªÙØŒ ÙÙŽØ³ÙŽÙ…ÙØ¹Ù’ØªÙÙ‡Ù ÙŠÙŽÙ‚ÙÙˆÙ„Ù: ((ÙŠÙŽØ§ Ø£ÙŽÙŠÙÙ‘Ù‡ÙŽØ§ Ø§Ù„Ù†ÙŽÙ‘Ø§Ø³Ù! Ø¹ÙŽÙ„ÙŽÙ‰ ÙƒÙÙ„ÙÙ‘ Ø£ÙŽÙ‡Ù’Ù„Ù Ø¨ÙŽÙŠÙ’ØªÙ ÙÙÙ‰ ÙƒÙÙ„ÙÙ‘ Ø¹ÙŽØ§Ù…Ù Ø£ÙØ¶Ù’Ø­ÙÙŠÙŽÙ‘Ø©ÙŒ ÙˆÙŽØ¹ÙŽØªÙÙŠØ±ÙŽØ©ÙŒ. Ù‡ÙŽÙ„Ù’ ØªÙŽØ¯Ù’Ø±ÙÙ‰ Ù…ÙŽØ§ Ø§Ù„Ù’Ø¹ÙŽØªÙÙŠØ±ÙŽØ©ÙØŸ Ù‡ÙÙ‰ÙŽ Ø§Ù„ÙŽÙ‘ØªÙÙ‰ ØªÙØ³ÙŽÙ…ÙŽÙ‘Ù‰ Ø§Ù„Ø±ÙŽÙ‘Ø¬ÙŽØ¨ÙÙŠÙŽÙ‘Ø©Ù.))', 'Artinya:Kami berwuquf di â€˜Arafah bersama NabiÂ shallallahu â€˜alaihi wa sallam. Saya mendengar beliau berkata, â€˜Wahai manusia! Setiap satu keluarga di setiap tahun harus menyembelih dan juga Al-â€˜Atiirah. Apakah kamu tahu apa itu Al-â€˜Atiirah? Dia adalah yang dinamakan Ar-Rajabiyah2.â€3'),
(51, 'Qurban', 'ÙˆÙŽÙ‚ÙŽØ¯Ù’ Ø±ÙŽØ®Ù‘ÙŽØµÙŽ Ø¨ÙŽØ¹Ù’Ø¶Ù Ø£ÙŽÙ‡Ù’Ù„Ù Ø§Ù’Ù„Ø¹ÙÙ„Ù’Ù…Ù Ø£ÙŽÙ†Ù’ ÙŠÙØ¶ÙŽØ­Ù‘ÙÙ‰ÙŽ Ø¹ÙŽÙ†Ù Ø§Ù„Ù’Ù…ÙŽÙŠÙ‘ÙØªÙ ÙˆÙŽÙ„ÙŽÙ…Ù’ ÙŠÙŽØ±ÙŽ Ø¨ÙŽØ¹Ù’Ø¶ÙÙ‡ÙÙ…Ù’ Ø£ÙŽÙ†Ù’ ÙŠÙØ¶ÙŽØ­Ù‘ÙÙ‰ÙŽ Ø¹ÙŽÙ†Ù’Ù‡, ÙˆÙŽÙ‚ÙŽØ§Ù„ÙŽ Ø¹ÙŽØ¨Ù’Ø¯Ù Ø§Ù„Ù„Ù‡Ù Ø¨Ù’Ù†Ù Ø§Ù„Ù’Ù…ÙØ¨ÙŽØ§Ø±ÙŽÙƒÙ: Ø£ÙŽØ­ÙŽØ¨Ù‘Ù Ø¥ÙÙ„ÙŽÙŠÙ‘ÙŽ Ø£ÙŽÙ†Ù’ ÙŠÙŽØªÙŽØµÙŽØ¯ÙŽÙ‚ÙŽ ÙˆÙŽÙ„ÙŽØ§ ÙŠÙØ¶ÙŽØ­Ù‘ÙÙ‰ Ø¹ÙŽÙ†Ù’Ù‡ ÙˆÙŽØ¥ÙÙ†Ù’ Ø¶ÙŽØ­Ù‘ÙŽÙ‰ ÙÙŽÙ„ÙŽØ§ ÙŠÙŽØ£Ù’ÙƒÙÙ„Ù’ Ù…ÙÙ†Ù’Ù‡ÙŽØ§ Ø´ÙŽÙŠÙ’Ø¦Ù‹Ø§ ÙˆÙŽÙŠÙŽØªÙŽØµÙŽØ¯Ù‘ÙŽÙ‚Ù’ Ø¨ÙÙ‡ÙŽØ§ ÙƒÙÙ„Ù‘ÙŽÙ‡ÙŽØ§', 'Artinya:Sebagian ahli ilmu memberikan rukhshah (keringanan) untuk berqurban untuk orang yang sudah meninggal, sebagian lagi mengatakan tidak boleh. â€˜Abdullah bin Al-Mubarak berkata, â€˜Yang lebih aku sukai adalah dia cukup bersedekah dan tidak berqurban. Apabila dia berqurban (untuk orang yang telah meninggal) maka dia tidak boleh makan sedikit pun darinya, dia harus mensedekahkan seluruhnya.â€12'),
(52, 'Qurban', 'Ø¥ÙÙ†Ù‘ÙŽØ§ Ø£ÙŽØ¹Ù’Ø·ÙŽÙŠÙ’Ù†ÙŽØ§ÙƒÙŽ Ø§Ù„Ù’ÙƒÙŽÙˆÙ’Ø«ÙŽØ±ÙŽ ÙÙŽØµÙŽÙ„ÙÙ‘ Ù„ÙØ±ÙŽØ¨ÙÙ‘ÙƒÙŽ ÙˆÙŽØ§Ù†Ù’Ø­ÙŽØ±Ù’', 'Artinya:â€œSesungguhnya Kami telah memberikan karunia sangat banyak kepadamu, maka sholatlah untuk Tuhanmu dan sembelihlah qurban.â€(Surat Al Kautsar ayat 1-2)Â '),
(53, 'Qurban', 'ÙˆÙŽÙ„ÙÙƒÙÙ„Ù‘Ù Ø£ÙÙ…Ù‘ÙŽØ©Ù Ø¬ÙŽØ¹ÙŽÙ„Ù’Ù†ÙŽØ§ Ù…ÙŽÙ†Ø³ÙŽÙƒØ§Ù‹ Ù„ÙÙŠÙŽØ°Ù’ÙƒÙØ±ÙÙˆØ§ Ø§Ø³Ù’Ù…ÙŽ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽÙ„ÙŽÙ‰ Ù…ÙŽØ§ Ø±ÙŽØ²ÙŽÙ‚ÙŽÙ‡ÙÙ… Ù…Ù‘ÙÙ† Ø¨ÙŽÙ‡ÙÙŠÙ…ÙŽØ©Ù Ø§Ù„Ù’Ø£ÙŽÙ†Ù’Ø¹ÙŽØ§Ù…Ù ÙÙŽØ¥ÙÙ„ÙŽÙ‡ÙÙƒÙÙ…Ù’ Ø¥ÙÙ„ÙŽÙ‡ÙŒ ÙˆÙŽØ§Ø­ÙØ¯ÙŒ ÙÙŽÙ„ÙŽÙ‡Ù Ø£ÙŽØ³Ù’Ù„ÙÙ…ÙÙˆØ§ ÙˆÙŽØ¨ÙŽØ´Ù‘ÙØ±Ù Ø§Ù„Ù’Ù…ÙØ®Ù’Ø¨ÙØªÙÙŠÙ†ÙŽ', 'Artinya:â€œDan bagi tiap-tiap umat telah Kami syariatkan penyembelihan (kurban), supaya mereka menyebut nama Allah terhadap binatang ternak yang telah direzkikan Allah kepada mereka, maka Tuhanmu ialah Tuhan Yang Maha Esa, karena itu berserah dirilah kamu kepada-Nya. Dan berilah kabar gembira kepada orang-orang yang tunduk patuh (kepada Allah)â€ (QS: Al Hajj : 34)'),
(54, 'Qurban', 'ÙÙŽÙƒÙÙ„ÙÙˆØ§ Ù…ÙÙ†Ù’Ù‡ÙŽØ§ ÙˆÙŽØ£ÙŽØ·Ù’Ø¹ÙÙ…ÙÙˆØ§ Ø§Ù„Ù’Ù‚ÙŽØ§Ù†ÙØ¹ÙŽ ÙˆÙŽØ§Ù„Ù’Ù…ÙØ¹Ù’ØªÙŽØ±Ù‘ÙŽ Ù„ÙŽÙ†Ù’ ÙŠÙŽÙ†ÙŽØ§Ù„ÙŽ Ø§Ù„Ù„Ù‘ÙŽÙ‡ÙŽ Ù„ÙØ­ÙÙˆÙ…ÙÙ‡ÙŽØ§ ÙˆÙŽÙ„Ø§ Ø¯ÙÙ…ÙŽØ§Ø¤ÙÙ‡ÙŽØ§ ÙˆÙŽÙ„ÙŽÙƒÙÙ†Ù’ ÙŠÙŽÙ†ÙŽØ§Ù„ÙÙ‡Ù Ø§Ù„ØªÙ‘ÙŽÙ‚Ù’ÙˆÙŽÙ‰ Ù…ÙÙ†Ù’ÙƒÙÙ…Ù’', 'Artinya:â€œMaka makanlah sebagiannya (daging kurban) dan berilah makan orang yang merasa cukup dengan apa yang ada padanya (orang yang tidak meminta-minta) dan orang yang meminta. Daging-daging qurban dan darahnya itu sekali-kali tidak dapat mencapai (keridhaan) Allah, tetapi ketakwaan dari kamulah yang dapat mencapainya.â€(Surat Al Hajj ayat 36-37)'),
(56, 'Qurban', 'Ù‚ÙÙ„Ù’ Ø¥ÙÙ†Ù‘ÙŽ ØµÙŽÙ„ÙŽØ§ØªÙÙŠ ÙˆÙŽÙ†ÙØ³ÙÙƒÙÙŠ ÙˆÙŽÙ…ÙŽØ­Ù’ÙŠÙŽØ§ÙŠÙŽ ÙˆÙŽÙ…ÙŽÙ…ÙŽØ§ØªÙÙŠ Ù„ÙÙ„Ù‘ÙŽÙ‡Ù Ø±ÙŽØ¨Ù‘Ù Ø§Ù„Ù’Ø¹ÙŽØ§Ù„ÙŽÙ…ÙÙŠÙ†ÙŽ Ù„ÙŽØ§ Ø´ÙŽØ±ÙÙŠÙƒÙŽ Ù„ÙŽÙ‡Ù ÙˆÙŽØ¨ÙØ°ÙŽÙ„ÙÙƒÙŽ Ø£ÙÙ…ÙØ±Ù’ØªÙ ÙˆÙŽØ£ÙŽÙ†ÙŽØ§ Ø£ÙŽÙˆÙ‘ÙŽÙ„Ù Ø§Ù„Ù’Ù…ÙØ³Ù’Ù„ÙÙ…ÙÙŠÙ†ÙŽ', 'Artinya:â€œKatakanlah: Sesungguhnya shalatku, sembelihanku, hidupku dan matiku hanyalah untuk Allah, Tuhan semesta alam. Tiada sekutu bagi-Nya dan demikian itulah yang diperintahkan kepadaku dan aku adalah orang yang pertama-tama menyerahkan diri (kepada Allah)â€ (Surat Al An-am ayat ke 162-163)'),
(57, 'Qurban', 'Â ÙˆÙŽÙ„ÙŽÙ‡Ù: Ù…ÙÙ†Ù’ Ø­ÙŽØ¯ÙÙŠØ«Ù Ø¹ÙŽØ§Ø¦ÙØ´ÙŽØ©ÙŽ Ø±ÙŽØ¶ÙÙŠÙŽ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽÙ†Ù’Ù‡ÙŽØ§; { Ø£ÙŽÙ…ÙŽØ±ÙŽ Ø¨ÙÙƒÙŽØ¨Ù’Ø´Ù Ø£ÙŽÙ‚Ù’Ø±ÙŽÙ†ÙŽ, ÙŠÙŽØ·ÙŽØ£Ù ÙÙÙŠ Ø³ÙŽÙˆÙŽØ§Ø¯Ù, ÙˆÙŽÙŠÙŽØ¨Ù’Ø±ÙÙƒÙ ÙÙÙŠ Ø³ÙŽÙˆÙŽØ§Ø¯Ù, ÙˆÙŽÙŠÙŽÙ†Ù’Ø¸ÙØ±Ù ÙÙÙŠ Ø³ÙŽÙˆÙŽØ§Ø¯Ù; Ù„ÙÙŠÙØ¶ÙŽØ­ÙÙ‘ÙŠÙŽ Ø¨ÙÙ‡Ù, ÙÙŽÙ‚ÙŽØ§Ù„ÙŽ: \"Ø§ÙØ´Ù’Ø­ÙŽØ°ÙÙŠ Ø§Ù„Ù’Ù…ÙØ¯Ù’ÙŠÙŽØ©ÙŽ\" , Ø«ÙÙ…Ù‘ÙŽ Ø£ÙŽØ®ÙŽØ°ÙŽÙ‡ÙŽØ§, ÙÙŽØ£ÙŽØ¶Ù’Ø¬ÙŽØ¹ÙŽÙ‡Ù, Ø«ÙÙ…Ù‘ÙŽ Ø°ÙŽØ¨ÙŽØ­ÙŽÙ‡Ù, ÙˆÙŽÙ‚ÙŽØ§Ù„ÙŽ: \"Ø¨ÙØ³Ù’Ù…Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù, Ø§ÙŽÙ„Ù„Ù‘ÙŽÙ‡ÙÙ…Ù‘ÙŽ ØªÙŽÙ‚ÙŽØ¨Ù‘ÙŽÙ„Ù’ Ù…ÙÙ†Ù’ Ù…ÙØ­ÙŽÙ…Ù‘ÙŽØ¯Ù ÙˆÙŽØ¢Ù„Ù Ù…ÙØ­ÙŽÙ…Ù‘ÙŽØ¯Ù, ÙˆÙŽÙ…ÙÙ†Ù’ Ø£ÙÙ…Ù‘Ø©Ù Ù…ÙØ­ÙŽÙ…Ù‘ÙŽØ¯Ù\"', 'Artinya:â€Beliau pernah memerintahkan untuk dibawakan dua ekor kambing kibas bertanduk, yang kaki, perut dan sekitar matanya berwarna hitam. Maka dibawakanlah kambing tersebut kepada beliau untuk dijadikan qurban. Beliaupun berkata kepada Aisyah, \"Wahai Aisyah, ambilkan pisau.\" Kemudian beliau mengambilnya, membaringkannya dan menyembelihnya seraya berdoa: \"Bismillaah, alloohumma taqobbal min muhammadin wa-aali muhammad, wa min ummati muhammad.â€Â '),
(58, 'Qurban', 'ÙˆÙŽØ¹ÙŽÙ†Ù’ Ø¬ÙÙ†Ù’Ø¯ÙØ¨Ù Ø¨Ù’Ù†Ù Ø³ÙÙÙ’ÙŠÙŽØ§Ù†ÙŽ Ù‚ÙŽØ§Ù„ÙŽ: { Ø´ÙŽÙ‡ÙØ¯Ù’ØªÙ Ø§Ù„Ø£ÙŽØ¶Ù’Ø­ÙŽÙ‰ Ù…ÙŽØ¹ÙŽ Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… ÙÙŽÙ„ÙŽÙ…Ù‘ÙŽØ§ Ù‚ÙŽØ¶ÙŽÙ‰ ØµÙŽÙ„Ø§ØªÙŽÙ‡Ù Ø¨ÙØ§Ù„Ù†Ù‘ÙŽØ§Ø³Ù, Ù†ÙŽØ¸ÙŽØ±ÙŽ Ø¥ÙÙ„ÙŽÙ‰ ØºÙŽÙ†ÙŽÙ…Ù Ù‚ÙŽØ¯Ù’ Ø°ÙØ¨ÙØ­ÙŽØªÙ’, ÙÙŽÙ‚ÙŽØ§Ù„ÙŽ: \"Ù…ÙŽÙ†Ù’ Ø°ÙŽØ¨ÙŽØ­ÙŽ Ù‚ÙŽØ¨Ù’Ù„ÙŽ Ø§Ù„ØµÙ‘ÙŽÙ„Ø§Ø©Ù ÙÙŽÙ„Ù’ÙŠÙŽØ°Ù’Ø¨ÙŽØ­Ù’ Ø´ÙŽØ§Ø©Ù‹ Ù…ÙŽÙƒÙŽØ§Ù†ÙŽÙ‡ÙŽØ§, ÙˆÙŽÙ…ÙŽÙ†Ù’ Ù„ÙŽÙ…Ù’ ÙŠÙŽÙƒÙÙ†Ù’ Ø°ÙŽØ¨ÙŽØ­ÙŽ ÙÙŽÙ„Ù’ÙŠÙŽØ°Ù’Ø¨ÙŽØ­Ù’ Ø¹ÙŽÙ„ÙŽÙ‰ Ø§Ø³Ù’Ù…Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù\" } Ù…ÙØªÙ‘ÙŽÙÙŽÙ‚ÙŒ Ø¹ÙŽÙ„ÙŽÙŠÙ’Ù‡ Ù', 'Artinya:â€Barangsiapa menyembelih sebelum shalat, hendaknya ia menyembelih seekor kambing lagi sebagai gantinya. Barangsiapa belum menyembelih, hendaknya ia menyembelih dengan nama Allah.â€'),
(59, 'Qurban', 'ÙˆÙŽØ¹ÙŽÙ†Ù Ø§Ù„Ù’Ø¨ÙŽØ±ÙŽØ§Ø¡Ù Ø¨Ù†Ù Ø¹ÙŽØ§Ø²ÙØ¨Ù Ø±ÙŽØ¶ÙÙŠÙŽ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽÙ†Ù’Ù‡ÙÙ…ÙŽØ§ Ù‚ÙŽØ§Ù„ÙŽ: Ù‚ÙŽØ§Ù…ÙŽ ÙÙÙŠÙ†ÙŽØ§ Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… ÙÙŽÙ‚ÙŽØ§Ù„ÙŽ: { \"Ø£ÙŽØ±Ù’Ø¨ÙŽØ¹ÙŒ Ù„Ø§ ØªÙŽØ¬ÙÙˆØ²Ù ÙÙÙŠ Ø§Ù„Ø¶Ù‘ÙŽØ­ÙŽØ§ÙŠÙŽØ§: Ø§ÙŽÙ„Ù’Ø¹ÙŽÙˆÙ’Ø±ÙŽØ§Ø¡Ù Ø§Ù„Ù’Ø¨ÙŽÙŠÙÙ‘Ù†Ù Ø¹ÙŽÙˆÙŽØ±ÙÙ‡ÙŽØ§, ÙˆÙŽØ§Ù„Ù’Ù…ÙŽØ±ÙÙŠØ¶ÙŽØ©Ù Ø§Ù„Ù’Ø¨ÙŽÙŠÙÙ‘Ù†Ù Ù…ÙŽØ±ÙŽØ¶ÙÙ‡ÙŽØ§, ÙˆÙŽØ§Ù„Ù’Ø¹ÙŽØ±Ù’Ø¬ÙŽØ§Ø¡Ù Ø§Ù„Ù’Ø¨ÙŽÙŠÙÙ‘Ù†Ù Ø¸ÙŽÙ„Ù’Ø¹ÙÙ‡ÙŽ Ø§ ÙˆÙŽØ§Ù„Ù’ÙƒÙŽØ³ÙÙŠØ±ÙŽØ©Ù Ø§Ù„Ù‘ÙŽØªÙÙŠ Ù„Ø§ ØªÙÙ†Ù’Ù‚ÙÙŠ\" } Ø±ÙŽÙˆÙŽØ§Ù‡Ù Ø§Ù„Ù’Ø®ÙŽÙ…Ù’Ø³ÙŽØ© Ù . ÙˆÙŽØµÙŽØ­Ù‘ÙŽØ­ÙŽÙ‡Ù Ø§Ù„ØªÙ‘ÙØ±Ù’Ù…ÙØ°ÙÙŠÙ‘Ù, ÙˆÙŽØ§Ø¨Ù’Ù†Ù Ø­ÙØ¨Ù‘ÙŽØ§Ù†Â ', 'Artinya:â€Empat macam hewan yang tidak boleh dijadikan qurban, yaitu: hewan yang tampak jelas butanya, tampak jelas sakitnya, tampak jelas pincangnya, dan hewan tua yang tidak bersumsum.â€'),
(60, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø¹ÙŽØ·ÙŽØ§Ø¡Ù Ø¨Ù’Ù†Ù ÙŠÙŽØ³ÙŽØ§Ø±Ù Ù‚ÙŽØ§Ù„ÙŽ: Ø³ÙŽØ£ÙŽÙ„Ù’ØªÙ Ø§ÙŽØ¨ÙŽØ§ Ø§ÙŽÙŠÙ‘ÙÙˆÙ’Ø¨ÙŽ Ø§Ù’Ù„Ø§ÙŽÙ†Ù’ØµÙŽØ§Ø±ÙÙŠÙ‘ÙŽ: ÙƒÙŽÙŠÙ’ÙÙŽ ÙƒÙŽØ§Ù†ÙŽØªÙ Ø§Ù„Ø¶Ù‘ÙŽØ­ÙŽØ§ÙŠÙŽØ§ ÙÙÙŠÙ’ÙƒÙÙ…Ù’ Ø¹ÙŽÙ„ÙŽÙ‰ Ø¹ÙŽÙ‡Ù’Ø¯Ù Ø±ÙŽØ³ÙÙˆÙ’Ù„Ù Ø§Ù„Ù„Ù‡Ù ØµØŸ Ù‚ÙŽØ§Ù„ÙŽ: ÙƒÙŽØ§Ù†ÙŽ Ø§Ù„Ø±Ù‘ÙŽØ¬ÙÙ„Ù ÙÙÙ‰ Ø¹ÙŽÙ‡Ù’Ø¯Ù Ø§Ù„Ù†Ù‘ÙŽØ¨ÙÙŠÙ‘ Øµ ÙŠÙØ¶ÙŽØ­Ù‘Ù‰ Ø¨ÙØ§Ù„Ø´Ù‘ÙŽØ§Ø©Ù Ø¹ÙŽÙ†Ù’Ù‡Ù ÙˆÙŽ Ø¹ÙŽÙ†Ù’ Ø§ÙŽÙ‡Ù’Ù„Ù Ø¨ÙŽÙŠÙ’ØªÙÙ‡Ù. ÙÙŽÙŠÙŽØ£Ù’ÙƒÙÙ„ÙÙˆÙ’Ù†ÙŽ ÙˆÙŽ ÙŠÙØ·Ù’Ø¹ÙÙ…ÙÙˆÙ’Ù†ÙŽ Ø­ÙŽØªÙ‘ÙŽÙ‰ ØªÙŽØ¨ÙŽØ§Ù‡ÙŽÙ‰ Ø§Ù„Ù†Ù‘ÙŽØ§Ø³Ù ÙÙŽØµÙŽØ§Ø±ÙŽ ÙƒÙŽÙ…ÙŽØ§ ØªÙŽØ±ÙŽÙ‰. Ø§Ø¨Ù† Ù…Ø§Ø¬Ù‡ Ùˆ Ø§Ù„ØªØ±Ù…Ø°Ù‰ Ùˆ ØµØ­Ø­Ù‡ØŒ ÙÙ‰ Ù†ÙŠÙ„ Ø§Ù„Ø§ÙˆØ·Ø§Ø± 5: 136Â ', 'Dari Atha bin Yasar dia berkata : Saya bertanya kepada Abu Ayyub Al-Anshariy, \"Bagaimanakah udlhiyah yang dilakukan di masa Rasulullah SAW?\". Jawabnya, \"Seorang laki-laki di zaman Rasulullah SAW menyembelih seekor kambing untuknya dan untuk ahli baitnya (rumah tangganya), lalu mereka makan dagingnya itu dan memberi makan kepada orang lain, sehingga manusia bermegah-megah dengan qurban itu sehingga menjadi seperti yang engkau saksikan sekarang ini\". [HR. Ibnu Majah dan Tirmidzi]Â '),
(61, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ù†ÙØ¨ÙŽÙŠÙ’Ø´ÙŽØ©ÙŽØ› Ø£ÙŽÙ†Ù‘ÙŽ Ø±ÙŽØ³ÙÙˆÙ„ÙŽ Ø§Ù„Ù„Ù‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… Ù‚ÙŽØ§Ù„ÙŽ ((ÙƒÙÙ†Ù’ØªÙ Ù†ÙŽÙ‡ÙŽÙŠÙ’ØªÙÙƒÙÙ…Ù’ Ø¹ÙŽÙ†Ù’ Ù„ÙØ­ÙÙˆÙ…Ù Ø§Ù„Ø£ÙŽØ¶ÙŽØ§Ø­ÙÙŠÙÙ‘ ÙÙŽÙˆÙ’Ù‚ÙŽ Ø«ÙŽÙ„Ø§ÙŽØ«ÙŽØ©Ù Ø£ÙŽÙŠÙ‘ÙŽØ§Ù…Ù. ÙÙŽÙƒÙÙ„ÙÙˆØ§ ÙˆÙŽØ§Ø¯Ù‘ÙŽØ®ÙØ±ÙÙˆØ§))', 'Artinya:â€œDulu aku pernah melarang kalian untuk menyimpan daging kurban lebih dari tiga hari,Â  maka kini makanlah dan simpanlah.â€'),
(62, 'Qurban', 'Â Ù‚ÙŽØ§Ù„ÙŽ Ø¬ÙÙ†Ù’Ø¯ÙŽØ¨ÙŒØŒ ÙƒÙŽØ§Ù†ÙŽ Ø§Ù„Ù†Ù‘ÙŽØ¨ÙÙŠÙ‘Ù Øµ ÙŠÙØµÙŽÙ„Ù‘Ù‰ Ø¨ÙÙ†ÙŽØ§ ÙŠÙŽÙˆÙ’Ù…ÙŽ Ø§Ù’Ù„ÙÙØ·Ù’Ø±Ù ÙˆÙŽ Ø§Ù„Ø´Ù‘ÙŽÙ…Ù’Ø³Ù Ø¹ÙŽÙ„ÙŽÙ‰ Ù‚ÙŽÙŠÙ’Ø¯Ù Ø±ÙÙ…Ù’Ø­ÙŽÙŠÙ’Ù†Ù ÙˆÙŽ Ø§Ù’Ù„Ø§ÙŽØ¶Ù’Ø­ÙŽÙ‰ Ø¹ÙŽÙ„ÙŽÙ‰ Ù‚ÙŽÙŠÙ’Ø¯Ù Ø±ÙÙ…Ù’Ø­Ù. Ø§Ø­Ù…Ø¯ Ø¨Ù† Ø­Ø³Ù†', 'Artinya:Telah berkata Jundab, \"Adalah Nabi SAW shalat Iedul Fithri bersama kami, sedang matahari tingginya kadar dua batang tombak, dan (beliau shalat) Iedul Adlha (diwaktu matahari) tingginya kadar satu batang tombak\". [HR. Ahmad bin Hasan]'),
(63, 'Qurban', 'Ø¹ÙŽÙ†Ù Ø§Ø¨Ù’Ù†Ù Ø¹ÙŽØ¨Ù‘ÙŽØ§Ø³Ù Ù‚ÙŽØ§Ù„ÙŽ: Ù‚ÙŽÙ„Ù‘ÙŽØªÙ Ø§Ù’Ù„Ø§ÙØ¨ÙÙ„Ù Ø¹ÙŽÙ„ÙŽÙ‰ Ø¹ÙŽÙ‡Ù’Ø¯Ù Ø±ÙŽØ³ÙÙˆÙ’Ù„Ù Ø§Ù„Ù„Ù‡Ù Øµ ÙÙŽØ§ÙŽÙ…ÙŽØ±ÙŽÙ‡ÙÙ…Ù’ Ø§ÙŽÙ†Ù’ ÙŠÙŽÙ†Ù’Ø­ÙŽØ±ÙÙˆØ§ Ø§Ù’Ù„Ø¨ÙŽÙ‚ÙŽØ±ÙŽ. Ø§Ø¨Ù† Ù…Ø§Ø¬Ù‡ 2: 1047ØŒ Ø±Ù‚Ù…: 3134Â ', 'Artinya:Dari Ibnu Abbas, ia berkata : Pernah terjadi pada jaman Rasulullah SAW (jumlah) unta sedikit, maka beliau menyuruh para shahabat berqurban dengan lembu. [HR. Ibnu Majah juz 2, hal. 1047, no. 3134].Â '),
(64, 'Qurban', 'Ø­ÙŽØ¯Ù‘ÙŽØ«ÙŽÙ†ÙŽØ§ Ø¹ÙŽØ¨Ù’Ø¯Ù Ø§Ù„Ø±Ù‘ÙŽØ­Ù’Ù…ÙŽÙ†Ù Ø¨Ù’Ù†Ù Ø¥ÙØ¨Ù’Ø±ÙŽØ§Ù‡ÙÙŠÙ…ÙŽ Ø§Ù„Ø¯Ù‘ÙÙ…ÙŽØ´Ù’Ù‚ÙÙŠÙ‘Ù Ø­ÙŽØ¯Ù‘ÙŽØ«ÙŽÙ†ÙŽØ§ Ø¹ÙŽØ¨Ù’Ø¯Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø§Ø¨Ù’Ù†Ù Ù†ÙŽØ§ÙÙØ¹Ù Ø­ÙŽØ¯Ù‘ÙŽØ«ÙŽÙ†ÙÙŠ Ø£ÙŽØ¨ÙÙˆ Ø§Ù„Ù’Ù…ÙØ«ÙŽÙ†Ù‘ÙŽÙ‰ Ø¹ÙŽÙ†Ù’ Ù‡ÙØ´ÙŽØ§Ù…Ù Ø¨Ù’Ù†Ù Ø¹ÙØ±Ù’ÙˆÙŽØ©ÙŽ Ø¹ÙŽÙ†Ù’ Ø£ÙŽØ¨ÙÙŠÙ‡Ù Ø¹ÙŽÙ†Ù’ Ø¹ÙŽØ§Ø¦ÙØ´ÙŽØ©ÙŽ Ø£ÙŽÙ†Ù‘ÙŽ Ø§Ù„Ù†Ù‘ÙŽØ¨ÙÙŠÙ‘ÙŽ ØµÙŽÙ„Ù‘ÙŽÙ‰ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽÙ„ÙŽÙŠÙ’Ù‡Ù ÙˆÙŽØ³ÙŽÙ„Ù‘ÙŽÙ…ÙŽ Ù‚ÙŽØ§Ù„ÙŽ Ù…ÙŽØ§ Ø¹ÙŽÙ…ÙÙ„ÙŽ Ø§Ø¨Ù’Ù†Ù Ø¢Ø¯ÙŽÙ…ÙŽ ÙŠÙŽÙˆÙ’Ù…ÙŽ Ø§Ù„Ù†Ù‘ÙŽØ­Ù’Ø±Ù Ø¹ÙŽÙ…ÙŽÙ„Ù‹Ø§ Ø£ÙŽØ­ÙŽØ¨Ù‘ÙŽ Ø¥ÙÙ„ÙŽÙ‰ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽØ²Ù‘ÙŽ ÙˆÙŽØ¬ÙŽÙ„Ù‘ÙŽ Ù…ÙÙ†Ù’ Ù‡ÙØ±ÙŽØ§Ù‚ÙŽØ©Ù Ø¯ÙŽÙ…Ù ÙˆÙŽØ¥ÙÙ†Ù‘ÙŽÙ‡Ù Ù„ÙŽÙŠÙŽØ£Ù’ØªÙÙŠ ÙŠÙŽÙˆÙ’Ù…ÙŽ Ø§Ù„Ù’Ù‚ÙÙŠÙŽØ§Ù…ÙŽØ©Ù Ø¨ÙÙ‚ÙØ±ÙÙˆÙ†ÙÙ‡ÙŽØ§ ÙˆÙŽØ£ÙŽØ¸Ù’Ù„ÙŽØ§ÙÙÙ‡ÙŽØ§ ÙˆÙŽØ£ÙŽØ´Ù’Ø¹ÙŽØ§Ø±ÙÙ‡ÙŽØ§ ÙˆÙŽØ¥ÙÙ†Ù‘ÙŽ Ø§Ù„Ø¯Ù‘ÙŽÙ…ÙŽ Ù„ÙŽÙŠÙŽÙ‚ÙŽØ¹Ù Ù…ÙÙ†Ù’ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽØ²Ù‘ÙŽ ÙˆÙŽØ¬ÙŽÙ„Ù‘ÙŽ Ø¨ÙÙ…ÙŽÙƒÙŽØ§Ù†Ù Ù‚ÙŽØ¨Ù’Ù„ÙŽ Ø£ÙŽÙ†Ù’ ÙŠÙŽÙ‚ÙŽØ¹ÙŽ Ø¹ÙŽÙ„ÙŽÙ‰ Ø§Ù„Ù’Ø£ÙŽØ±Ù’Ø¶Ù ÙÙŽØ·ÙÙŠØ¨ÙÙˆØ§ Ø¨ÙÙ‡ÙŽØ§ Ù†ÙŽÙÙ’Ø³Ù‹Ø§Â ', 'Artinya:â€œTidak ada amalan yang dikerjakan anak Adam ketika hari (raya) kurban yang lebih dicintai oleh Allah Azza Wa Jalla dari mengalirkan darah, sesungguhnya pada hari kiamat ia akan datang dgn tanduk-tanduknya, kuku-kukunya & bulu-bulunya. Dan sesungguhnya darah tersebut akan sampai kepada Allah Azza Wa Jalla sebelum jatuh ke tanah, maka perbaguslah jiwa kalian dengannya.â€ [HR. ibnumajah No.3117].Â '),
(65, 'Qurban', 'Ø­ÙŽØ¯Ù‘ÙŽØ«ÙŽÙ†ÙŽØ§ Ù…ÙØ­ÙŽÙ…Ù‘ÙŽØ¯Ù Ø¨Ù’Ù†Ù Ø®ÙŽÙ„ÙŽÙÙ Ø§Ù„Ù’Ø¹ÙŽØ³Ù’Ù‚ÙŽÙ„ÙŽØ§Ù†ÙÙŠÙ‘Ù Ø­ÙŽØ¯Ù‘ÙŽØ«ÙŽÙ†ÙŽØ§ Ø¢Ø¯ÙŽÙ…Ù Ø¨Ù’Ù†Ù Ø£ÙŽØ¨ÙÙŠ Ø¥ÙÙŠÙŽØ§Ø³Ù Ø­ÙŽØ¯Ù‘ÙŽØ«ÙŽÙ†ÙŽØ§ Ø³ÙŽÙ„Ù‘ÙŽØ§Ù…Ù Ø¨Ù’Ù†Ù Ù…ÙØ³Ù’ÙƒÙÙŠÙ†Ù Ø­ÙŽØ¯Ù‘ÙŽØ«ÙŽÙ†ÙŽØ§ Ø¹ÙŽØ§Ø¦ÙØ°Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽÙ†Ù’ Ø£ÙŽØ¨ÙÙŠ Ø¯ÙŽØ§ÙˆÙØ¯ÙŽ Ø¹ÙŽÙ†Ù’ Ø²ÙŽÙŠÙ’Ø¯Ù Ø¨Ù’Ù†Ù Ø£ÙŽØ±Ù’Ù‚ÙŽÙ…ÙŽ Ù‚ÙŽØ§Ù„ÙŽ Ù‚ÙŽØ§Ù„ÙŽ Ø£ÙŽØµÙ’Ø­ÙŽØ§Ø¨Ù Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù ØµÙŽÙ„Ù‘ÙŽÙ‰ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽÙ„ÙŽÙŠÙ’Ù‡Ù ÙˆÙŽØ³ÙŽÙ„Ù‘ÙŽÙ…ÙŽ ÙŠÙŽØ§ Ø±ÙŽØ³ÙÙˆÙ„ÙŽ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ù…ÙŽØ§ Ù‡ÙŽØ°ÙÙ‡Ù Ø§Ù„Ù’Ø£ÙŽØ¶ÙŽØ§Ø­ÙÙŠÙ‘Ù Ù‚ÙŽØ§Ù„ÙŽ Ø³ÙÙ†Ù‘ÙŽØ©Ù Ø£ÙŽØ¨ÙÙŠÙƒÙÙ…Ù’ Ø¥ÙØ¨Ù’Ø±ÙŽØ§Ù‡ÙÙŠÙ…ÙŽ Ù‚ÙŽØ§Ù„ÙÙˆØ§ ÙÙŽÙ…ÙŽØ§ Ù„ÙŽÙ†ÙŽØ§ ÙÙÙŠÙ‡ÙŽØ§ ÙŠÙŽØ§ Ø±ÙŽØ³ÙÙˆÙ„ÙŽ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ù‚ÙŽØ§Ù„ÙŽ Ø¨ÙÙƒÙÙ„Ù‘Ù Ø´ÙŽØ¹ÙŽØ±ÙŽØ©Ù Ø­ÙŽØ³ÙŽÙ†ÙŽØ©ÙŒ Ù‚ÙŽØ§Ù„ÙÙˆØ§ ÙÙŽØ§Ù„ØµÙ‘ÙÙˆÙÙ ÙŠÙŽØ§ Ø±ÙŽØ³ÙÙˆÙ„ÙŽ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ù‚ÙŽØ§Ù„ÙŽ Ø¨ÙÙƒÙÙ„Ù‘Ù Ø´ÙŽØ¹ÙŽØ±ÙŽØ©Ù Ù…ÙÙ†Ù’ Ø§Ù„ØµÙ‘ÙÙˆÙÙ Ø­ÙŽØ³ÙŽÙ†ÙŽØ©ÙŒÂ ', 'Artinya:â€œBerkata kepada kami Muhammad bin Khalaf Al â€˜Asqalani, berkata kepada kami Adam bin Abi Iyas, berkata kepada kami Sullam bin Miskin, berkata kepada kami Aidzullah, dari Abu Daud, dari Zaid bin Arqam, dia berkata: berkata para sahabat Rasulullah Shallallahu Alaihi wa Sallam: â€œWahai Rasulullah, hewan qurban apa ini?â€ Beliau bersabda: â€œIni adalah sunah bapak kalian, Ibrahim.â€ Mereka berkata: â€œLalu pada hewan tersebut, kami dapat apa wahai Rasulullah?â€ Beliau bersabda: â€œPada setiap bulu ada satu kebaikan.â€ Mereka berkata: â€œBagaimana dengan shuf (bulu domba)?â€ Beliau bersabda: â€œPada setiap bulu shuf ada satu kebaikan.â€ [HR. Riwayat Ibnu Majah dalam Sunannya No. 3127]Â '),
(66, 'Qurban', 'Ø£ÙŽØ±Ù’Ø¨ÙŽØ¹ÙŒ Ù„ÙŽØ§ ÙŠÙØ¶ÙŽØ­Ù‘ÙŽÙ‰ Ø¨ÙÙ‡ÙÙ†Ù‘ÙŽ: Ø§Ù„Ù’Ø¹ÙŽÙˆÙ’Ø±ÙŽØ§Ø¡Ù Ø§Ù„Ù’Ø¨ÙŽÙŠÙ‘ÙÙ†Ù Ø¹ÙŽÙˆÙŽØ±ÙÙ‡ÙŽØ§ØŒ ÙˆÙŽØ§Ù„Ù’Ù…ÙŽØ±ÙÙŠØ¶ÙŽØ©Ù Ø§Ù„Ù’Ø¨ÙŽÙŠÙ‘ÙÙ†Ù Ù…ÙŽØ±ÙŽØ¶ÙÙ‡ÙŽØ§ØŒ ÙˆÙŽØ§Ù„Ù’Ø¹ÙŽØ±Ù’Ø¬ÙŽØ§Ø¡Ù Ø§Ù„Ù’Ø¨ÙŽÙŠÙ‘ÙÙ†Ù Ø¸ÙŽÙ„ÙŽØ¹ÙÙ‡ÙŽØ§ØŒ ÙˆÙŽØ§Ù„Ù’Ø¹ÙŽØ¬Ù’ÙÙŽØ§Ø¡Ù Ø§Ù„Ù‘ÙŽØªÙÙŠ Ù„ÙŽØ§ ØªÙÙ†Ù’Ù‚ÙÙŠÙ’', 'Artinya:â€œAda empat macam yang tidak boleh dijadikan qurban. Yaitu, hewan yang rabun dan jelas kerabunannya, hewan yang sakit dan jelas sakitnya, hewan yang pincang dan jelas pincangnya, dan hewan yang kurus tidak berdagingâ€. (HR. Ibnu Hibban: Shahih)Â '),
(67, 'Qurban', 'Â Ø¹ÙŽÙ†Ù’ Ø£ÙŽÙ†ÙŽØ³Ù Ø¨Ù†Ù Ù…ÙŽØ§Ù„ÙÙƒÙÂ  { Ø£ÙŽÙ†Ù‘ÙŽ Ø§Ù„Ù†Ù‘ÙŽØ¨ÙÙŠÙ‘ÙŽ ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… ÙƒÙŽØ§Ù†ÙŽ ÙŠÙØ¶ÙŽØ­ÙÙ‘ÙŠ Ø¨ÙÙƒÙŽØ¨Ù’Ø´ÙŽÙŠÙ’Ù†Ù Ø£ÙŽÙ…Ù’Ù„ÙŽØ­ÙŽÙŠÙ’Ù†Ù, Ø£ÙŽÙ‚Ù’Ø±ÙŽÙ†ÙŽÙŠÙ’Ù†Ù, ÙˆÙŽÙŠÙØ³ÙŽÙ…ÙÙ‘ÙŠ, ÙˆÙŽÙŠÙÙƒÙŽØ¨ÙÙ‘Ø±Ù, ÙˆÙŽÙŠÙŽØ¶ÙŽØ¹Ù Ø±ÙØ¬Ù’Ù„ÙŽÙ‡Ù Ø¹ÙŽÙ„ÙŽÙ‰ ØµÙÙÙŽØ§Ø­ÙÙ‡ÙÙ…ÙŽØ§. ÙˆÙŽÙÙÙŠ Ù„ÙŽÙÙ’Ø¸Ù: Ø°ÙŽØ¨ÙŽØ­ÙŽÙ‡ÙÙ…ÙŽØ§ Ø¨ÙÙŠÙŽØ¯ÙÙ‡Ù }Â  Ù…ÙØªÙ‘ÙŽÙÙŽÙ‚ÙŒ Ø¹ÙŽÙ„ÙŽÙŠÙ’Ù‡ Ù ÙˆÙŽÙÙÙŠ Ù„ÙŽÙÙ’Ø¸Ù: { Ø³ÙŽÙ…ÙÙŠÙ†ÙŽÙŠÙ’Ù†Ù }Â Â Â  ÙˆÙŽÙ„ÙØ£ÙŽØ¨ÙÙŠ Ø¹ÙŽÙˆÙŽØ§Ù†ÙŽØ©ÙŽ ÙÙÙŠ \"ØµÙŽØ­ÙÙŠØ­ÙÙ‡Ù\" : { Ø«ÙŽÙ…ÙÙŠÙ†ÙŽÙŠÙ’Ù†Ù }Â  . Ø¨ÙØ§Ù„Ù’Ù…ÙØ«ÙŽÙ„Ù‘ÙŽØ«ÙŽØ©Ù Ø¨ÙŽØ¯ÙŽÙ„ÙŽ Ø§Ù„Ø³ÙÙ‘ÙŠÙ† ÙˆÙŽÙÙÙŠ Ù„ÙŽÙÙ’Ø¸Ù Ù„ÙÙ…ÙØ³Ù’Ù„ÙÙ…Ù, ÙˆÙŽÙŠÙŽÙ‚ÙÙˆÙ„Ù: { Ø¨ÙØ³Ù’Ù…Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù. ÙˆÙŽØ§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø£ÙŽÙƒÙ’Ø¨ÙŽØ±Ù }Â ', 'Artinya:â€Biasanya NabiÂ  biasanya berkurban dengan dua ekor kambing kibas putih yang bagus dan bertanduk.Â  Beliau menyebut nama Allah dan bertakbir,Â  dan beliau meletakkan kakinya di samping binatang itu.â€Â  Dalam suatu lafadz: â€beliau menyembelih dengan tangan beliau sendiri.â€Â  Dalam suatu lafadz: â€dua ekor kambing gemuk.â€Â  Menurut Abu Awanah: â€dua ekor kambing yang mahal.â€Â  dengan menggunakan huruf tsa,Â  bukan siin.Â  Dalam lafadz Muslim: â€Beliau membaca Bismillaahi walloohu akbar.â€Â '),
(68, 'Qurban', 'ÙˆÙŽØ¹ÙŽÙ†Ù’ Ø¹ÙŽÙ„ÙÙŠÙÙ‘ Ø¨Ù’Ù†Ù Ø£ÙŽØ¨ÙÙŠ Ø·ÙŽØ§Ù„ÙØ¨Ù Ù‚ÙŽØ§Ù„ÙŽ: { Ø£ÙŽÙ…ÙŽØ±ÙŽÙ†ÙÙŠ Ø§Ù„Ù†Ù‘ÙŽØ¨ÙÙŠÙ‘Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… Ø£ÙŽÙ†Ù‘ÙŽ Ø£ÙŽÙ‚Ù’ÙˆÙŽÙ…ÙŽ Ø¹ÙŽÙ„ÙŽÙ‰ Ø¨ÙØ¯Ù’Ù†ÙÙ‡Ù, ÙˆÙŽØ£ÙŽÙ†Ù’ Ø£ÙÙ‚ÙŽØ³ÙÙ‘Ù…ÙŽ Ù„ÙØ­ÙÙˆÙ…ÙŽÙ‡ÙŽØ§ ÙˆÙŽØ¬ÙÙ„ÙÙˆØ¯ÙŽÙ‡ÙŽØ§ ÙˆÙŽØ¬ÙÙ„Ø§Ù„ÙŽÙ‡ÙŽØ§ Ø¹ÙŽÙ„ÙŽÙ‰ Ø§Ù„Ù’Ù…ÙŽØ³ÙŽØ§ÙƒÙÙŠÙ†Ù, ÙˆÙŽÙ„Ø§ Ø£ÙØ¹Ù’Ø·ÙÙŠÙŽ ÙÙÙŠ Ø¬ÙØ²ÙŽØ§Ø±ÙŽØªÙÙ‡ÙŽØ§ Ù…ÙÙ†Ù’Ù‡ÙŽØ§ Ø´ÙŽÙŠÙ’Ø¦Ø§Ù‹ } Ù…ÙØªÙ‘ÙŽÙÙŽÙ‚ÙŒ Ø¹ÙŽÙ„ÙŽÙŠÙ’Ù‡ Ù', 'Artinya:â€Rasulullah memerintahkan kepadaku untuk mengurusi hewan kurbannya, membagi-bagikan dagingnya, kulit dan pakaiannya kepada orang-orang miskin, dan aku tidak diperbolehkan memberi sesuatu apapun dari hewan kurban (sebagai upah) kepada penyembelihnya.â€'),
(69, 'Qurban', 'Ø¥ÙÙ†Ù‘ÙŽ Ø£ÙŽÙˆÙ‘ÙŽÙ„ÙŽ Ù…ÙŽØ§ Ù†ÙŽØ¨Ù’Ø¯ÙŽØ£Ù Ø¨ÙÙ‡Ù ÙÙÙŠÙ’ ÙŠÙŽÙˆÙ’Ù…ÙÙ†ÙŽØ§ Ù‡ÙŽØ°ÙŽØ§ Ø£ÙŽÙ†Ù’ Ù†ÙØµÙŽÙ„Ù‘ÙÙŠÙŽ Ø«ÙÙ…Ù‘ÙŽ Ù†ÙŽØ±Ù’Ø¬ÙØ¹ÙŽ ÙÙŽÙ†ÙŽÙ†Ù’Ø­ÙŽØ±ÙŽÂ ', 'Artinya:â€œSesungguhnya yang pertama kali kita lakukan pada hari ini adalah menunaikan shalat (idul Adha), kemudian pulang lalu menyembelih hewan kurbanâ€. (HR. Bukhari)Â '),
(70, 'Qurban', 'Â Ø¹ÙŽÙ†Ù’ Ø¬ÙŽØ§Ø¨ÙØ±Ù Ù‚ÙŽØ§Ù„ÙŽ: Ù‚ÙŽØ§Ù„ÙŽ Ø±ÙŽØ³ÙÙˆÙ’Ù„Ù Ø§Ù„Ù„Ù‡Ù Øµ Ù„Ø§ÙŽ ØªÙŽØ°Ù’Ø¨ÙŽØ­ÙÙˆÙ’Ø§ Ø§ÙÙ„Ø§Ù‘ÙŽ Ù…ÙØ³ÙÙ†Ù‘ÙŽØ©Ù‹ Ø§ÙÙ„Ø§Ù‘ÙŽ Ø§ÙŽÙ†Ù’ ÙŠÙŽØ¹Ù’Ø³ÙØ±ÙŽ Ø¹ÙŽÙ„ÙŽÙŠÙ’ÙƒÙÙ…Ù’ ÙÙŽØªÙŽØ°Ù’Ø¨ÙŽØ­ÙÙˆÙ’Ø§ Ø¬ÙŽØ°ÙŽØ¹ÙŽØ©Ù‹ Ù…ÙÙ†ÙŽ Ø§Ù„Ø¶Ù‘ÙŽØ£Ù’Ù†Ù. Ù…Ø³Ù„Ù… 3: 1555', 'Artinya:Dari Jabir, ia berkata : Rasulullah SAW bersabda, \"Janganlah kamu menyembelih untuk qurban melainkan yang Musinnah (telah berganti gigi) kecuali jika sukar didapati, maka boleh kamu menyembelih jadza-ah (yang berumur 1 tahun) dari kambingâ€. [HR. Muslim]Â '),
(71, 'Qurban', 'Ø¥ÙØ°ÙŽØ§ Ø±ÙŽØ£ÙŽÙŠÙ’ØªÙÙ…Ù’ Ù‡ÙÙ„ÙŽØ§Ù„ÙŽ Ø°ÙÙŠ Ø§Ù„Ù’Ø­ÙØ¬Ù‘ÙŽØ©Ù ÙˆÙŽØ£ÙŽØ±ÙŽØ§Ø¯ÙŽ Ø£ÙŽØ­ÙŽØ¯ÙÙƒÙÙ…Ù’ Ø£ÙŽÙ†Ù’ ÙŠÙØ¶ÙŽØ­Ù‘ÙÙŠÙŽ ÙÙŽÙ„Ù’ÙŠÙÙ…Ù’Ø³ÙÙƒÙ’ Ø¹ÙŽÙ†Ù’ Ø´ÙŽØ¹Ù’Ø±ÙÙ‡Ù ÙˆÙŽØ£ÙŽØ¸Ù’ÙÙŽØ§Ø±ÙÙ‡ÙÂ ', 'Artinya:â€œSesungguhnya yang pertama kali kita lakukan pada hari ini adalah menunaikan shalat (idul Adha), kemudian pulang lalu menyembelih hewan kurbanâ€. (HR. Bukhari)'),
(72, 'Qurban', 'Â Ø¹ÙŽÙ†Ù’ Ø¬ÙŽØ§Ø¨ÙØ±Ù Ù‚ÙŽØ§Ù„ÙŽ: Ù‚ÙŽØ§Ù„ÙŽ Ø±ÙŽØ³ÙÙˆÙ’Ù„Ù Ø§Ù„Ù„Ù‡Ù Øµ Ù„Ø§ÙŽ ØªÙŽØ°Ù’Ø¨ÙŽØ­ÙÙˆÙ’Ø§ Ø§ÙÙ„Ø§Ù‘ÙŽ Ù…ÙØ³ÙÙ†Ù‘ÙŽØ©Ù‹ Ø§ÙÙ„Ø§Ù‘ÙŽ Ø§ÙŽÙ†Ù’ ÙŠÙŽØ¹Ù’Ø³ÙØ±ÙŽ Ø¹ÙŽÙ„ÙŽÙŠÙ’ÙƒÙÙ…Ù’ ÙÙŽØªÙŽØ°Ù’Ø¨ÙŽØ­ÙÙˆÙ’Ø§ Ø¬ÙŽØ°ÙŽØ¹ÙŽØ©Ù‹ Ù…ÙÙ†ÙŽ Ø§Ù„Ø¶Ù‘ÙŽØ£Ù’Ù†Ù. Ù…Ø³Ù„Ù… 3: 1555', 'Artinya:Dari Jabir, ia berkata : Rasulullah SAW bersabda, \"Janganlah kamu menyembelih untuk qurban melainkan yang Musinnah (telah berganti gigi) kecuali jika sukar didapati, maka boleh kamu menyembelih jadza-ah (yang berumur 1 tahun) dari kambingâ€. [HR. Muslim]Â '),
(73, 'Qurban', 'Ø¥ÙØ°ÙŽØ§ Ø±ÙŽØ£ÙŽÙŠÙ’ØªÙÙ…Ù’ Ù‡ÙÙ„ÙŽØ§Ù„ÙŽ Ø°ÙÙŠ Ø§Ù„Ù’Ø­ÙØ¬Ù‘ÙŽØ©Ù ÙˆÙŽØ£ÙŽØ±ÙŽØ§Ø¯ÙŽ Ø£ÙŽØ­ÙŽØ¯ÙÙƒÙÙ…Ù’ Ø£ÙŽÙ†Ù’ ÙŠÙØ¶ÙŽØ­Ù‘ÙÙŠÙŽ ÙÙŽÙ„Ù’ÙŠÙÙ…Ù’Ø³ÙÙƒÙ’ Ø¹ÙŽÙ†Ù’ Ø´ÙŽØ¹Ù’Ø±ÙÙ‡Ù ÙˆÙŽØ£ÙŽØ¸Ù’ÙÙŽØ§Ø±ÙÙ‡ÙÂ ', 'Artinya:â€œApa bila kalian telah meru-yah (melihat) bulan sabit Zulhijah, dan seseorang diantara kalian hendak memotong hewan kurban, maka hendaklah ia menahan diri untuk tidak memotong rambut dan kukunyaâ€. (HR. Muslim)Â '),
(74, 'Qurban', 'ÙƒÙÙ„Ù‘Ù Ø£ÙŽÙŠÙ‘ÙŽØ§Ù…Ù Ø§Ù„ØªÙ‘ÙŽØ´Ù’Ø±ÙÙŠÙ‚Ù Ø°ÙŽØ¨Ù’Ø­ÙŒ', 'Artinya:â€œSeluruh hari-hari tasyriq adalah waktu menyembelih hewan qurbanâ€. (HR. Ahmad; Shahih)'),
(75, 'Qurban', 'Ù„ÙŽØ§ ØªÙŽØ°Ù’Ø¨ÙŽØ­ÙÙˆØ§ Ø¥ÙÙ„Ù‘ÙŽØ§ Ù…ÙØ³ÙÙ†Ù‘ÙŽØ©Ù‹ Ø¥ÙÙ„Ù‘ÙŽØ§ Ø£ÙŽÙ†Ù’ ÙŠÙŽØ¹Ù’Ø³ÙØ±ÙŽ Ø¹ÙŽÙ„ÙŽÙŠÙ’ÙƒÙÙ…Ù’ ÙÙŽØªÙŽØ°Ù’Ø¨ÙŽØ­ÙÙˆØ§ Ø¬ÙŽØ°ÙŽØ¹ÙŽØ©Ù‹ Ù…ÙÙ†ÙŽ Ø§Ù„Ø¶Ù‘ÙŽØ£Ù’Ù†ÙÂ ', 'Artinya:â€œJanganlah kalian memotong hewan qurban kecuali yang telah cukup umur. Kecuali jika kalian kesulitan mendapatkannya, maka potonglah domba mudaâ€ (HR. Muslim).'),
(76, 'Qurban', 'Â ÙˆÙŽØ¹ÙŽÙ†Ù’ Ø¬ÙÙ†Ù’Ø¯ÙØ¨Ù Ø¨Ù’Ù†Ù Ø³ÙÙÙ’ÙŠÙŽØ§Ù†ÙŽÂ  Ù‚ÙŽØ§Ù„ÙŽ: { Ø´ÙŽÙ‡ÙØ¯Ù’ØªÙ Ø§Ù„Ø£ÙŽØ¶Ù’Ø­ÙŽÙ‰ Ù…ÙŽØ¹ÙŽ Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… ÙÙŽÙ„ÙŽÙ…Ù‘ÙŽØ§ Ù‚ÙŽØ¶ÙŽÙ‰ ØµÙŽÙ„Ø§ØªÙŽÙ‡Ù Ø¨ÙØ§Ù„Ù†Ù‘ÙŽØ§Ø³Ù, Ù†ÙŽØ¸ÙŽØ±ÙŽ Ø¥ÙÙ„ÙŽÙ‰ ØºÙŽÙ†ÙŽÙ…Ù Ù‚ÙŽØ¯Ù’ Ø°ÙØ¨ÙØ­ÙŽØªÙ’, ÙÙŽÙ‚ÙŽØ§Ù„ÙŽ: \"Ù…ÙŽÙ†Ù’ Ø°ÙŽØ¨ÙŽØ­ÙŽ Ù‚ÙŽØ¨Ù’Ù„ÙŽ Ø§Ù„ØµÙ‘ÙŽÙ„Ø§Ø©Ù ÙÙŽÙ„Ù’ÙŠÙŽØ°Ù’Ø¨ÙŽØ­Ù’ Ø´ÙŽØ§Ø©Ù‹ Ù…ÙŽÙƒÙŽØ§Ù†ÙŽÙ‡ÙŽØ§, ÙˆÙŽÙ…ÙŽÙ†Ù’ Ù„ÙŽÙ…Ù’ ÙŠÙŽÙƒÙÙ†Ù’ Ø°ÙŽØ¨ÙŽØ­ÙŽ ÙÙŽÙ„Ù’ÙŠÙŽØ°Ù’Ø¨ÙŽØ­Ù’ Ø¹ÙŽÙ„ÙŽÙ‰ Ø§Ø³Ù’Ù…Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù\" }Â  Ù…ÙØªÙ‘ÙŽÙÙŽÙ‚ÙŒ Ø¹ÙŽÙ„ÙŽÙŠÙ’Ù‡ ÙÂ ', 'Artinya:â€Barangsiapa menyembelih sebelum shalat,Â  hendaknya ia menyembelih seekor kambing lagi sebagai gantinya.Â  Barangsiapa belum menyembelih,Â  hendaknya ia menyembelih dengan nama Allah.â€Â '),
(77, 'Qurban', 'Â Ø¹ÙŽÙ†Ù’ Ù‚ÙŽØªÙŽØ§Ø¯ÙŽØ©ÙŽ Ø¨Ù’Ù†Ù Ø§Ù„Ù†Ù‘ÙØ¹Ù’Ù…ÙŽØ§Ù†Ù Ø§ÙŽÙ†Ù‘ÙŽ Ø§Ù„Ù†Ù‘ÙŽØ¨ÙÙŠÙ‘ÙŽ Øµ Ù‚ÙŽØ§Ù„ÙŽ: Ù„Ø§ÙŽ ØªÙŽØ¨ÙÙŠÙ’Ø¹ÙÙˆÙ’Ø§ Ù„ÙØ­ÙÙˆÙ’Ù…ÙŽ Ø§Ù’Ù„Ù‡ÙŽØ¯Ù’ÙŠÙ ÙˆÙŽ Ø§Ù’Ù„Ø§ÙŽØ¶ÙŽØ§Ø­ÙÙ‰ ÙÙŽÙƒÙÙ„ÙÙˆÙ’Ø§ ÙˆÙŽ ØªÙŽØµÙŽØ¯Ù‘ÙŽÙ‚ÙÙˆÙ’Ø§ ÙˆÙŽ Ø§Ø³Ù’ØªÙŽÙ…Ù’ØªÙØ¹ÙÙˆÙ’Ø§ Ø¨ÙØ¬ÙÙ„ÙÙˆÙ’Ø¯ÙÙ‡ÙŽØ§ ÙˆÙŽ Ù„Ø§ÙŽ ØªÙŽØ¨ÙÙŠÙ’Ø¹ÙÙˆÙ’Ù‡ÙŽØ§ØŒ ÙˆÙŽ Ø§ÙÙ†Ù’ Ø§ÙØ·Ù’Ø¹ÙÙ…Ù’ØªÙÙ…Ù’ Ù…ÙÙ†Ù’ Ù„ÙŽØ­Ù’Ù…ÙÙ‡ÙŽØ§ ÙÙŽÙƒÙÙ„ÙÙˆÙ’Ø§ Ø§ÙÙ†Ù’ Ø´ÙØ¦Ù’ØªÙÙ…Ù’. Ø§Ø­Ù…Ø¯ 5: 478ØŒ Ø±Ù‚Ù…: 16211Â ', 'Artinya:Dari Qatadah bin Numan, bahwasanya Nabi SAW bersabda, â€œJanganlah kalian menjual daging-daging Hadyi (denda hajji) dan daging udlhiyah (qurban), makanlah dan sedeqahkanlah dan manfaatkanlah kulitnya, dan janganlah kalian menjualnya. Dan apabila kalian diberi dagingnya, maka makanlah jika kalian mauâ€. [HR. Ahmad]Â '),
(78, 'Qurban', 'Â Ø¹ÙŽÙ†Ù’ Ø£ÙÙ…ÙÙ‘ Ø³ÙŽÙ„ÙŽÙ…ÙŽØ©ÙŽØ› Ù‚ÙŽØ§Ù„ÙŽØªÙ’: Ù‚ÙŽØ§Ù„ÙŽ Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… ((Ù…ÙŽÙ†Ù’ Ø±ÙŽØ£ÙŽÙ‰ Ù…ÙÙ†Ù’ÙƒÙÙ…Ù’ Ù‡ÙÙ„Ø§ÙŽÙ„ÙŽ Ø°ÙÙŠ Ø§Ù„Ù’Ø­ÙØ¬Ù‘ÙŽØ©ÙØŒ ÙÙŽØ£ÙŽØ±ÙŽØ§Ø¯ÙŽ Ø£ÙŽÙ†Ù’ ÙŠÙØ¶ÙŽØ­ÙÙ‘ÙŠÙŽØŒ ÙÙŽÙ„Ø§ÙŽ ÙŠÙŽÙ‚Ù’Ø±ÙŽØ¨ÙŽÙ†Ù‘ÙŽ Ù„ÙŽÙ‡Ù Ø´ÙŽØ¹ÙŽØ±Ø§Ù‹ ÙˆÙŽÙ„Ø§ÙŽ Ø¸ÙÙÙ’Ø±Ø§Ù‹))Â ', 'Artinya:â€œBarangsiapa di antara kalian mendapati awal bulan Dzulhijjah,Â  lalu dia ingin berkurban,Â  maka janganlah dia mendekati (sengaja menyisihkan) rambut dan kukunya.â€'),
(79, 'Qurban', 'ÙˆÙŽØ¹ÙŽÙ†Ù’ Ø¬ÙŽØ§Ø¨ÙØ±Ù Ù‚ÙŽØ§Ù„ÙŽ: Ù‚ÙŽØ§Ù„ÙŽ Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… { \"Ù„Ø§ ØªÙŽØ°Ù’Ø¨ÙŽØ­ÙÙˆØ§ Ø¥ÙÙ„Ø§Ù‘ÙŽ Ù…ÙØ³ÙÙ†Ù‘ÙŽØ©Ù‹, Ø¥ÙÙ„Ø§Ù‘ÙŽ Ø£ÙŽÙ†Ù’ ÙŠÙŽØ¹Ù’Ø³ÙØ±ÙŽ Ø¹ÙŽÙ„ÙŽÙŠÙ’ÙƒÙÙ…Ù’ ÙÙŽØªÙŽØ°Ù’Ø¨ÙŽØ­ÙÙˆØ§ Ø¬ÙŽØ°ÙŽØ¹ÙŽØ©Ù‹ Ù…ÙÙ†ÙŽ Ø§Ù„Ø¶Ù‘ÙŽØ£Ù’Ù†Ù\" } Ø±ÙŽÙˆÙŽØ§Ù‡Ù Ù…ÙØ³Ù’Ù„ÙÙ…Â ', 'Artinya:â€Janganlah kalian menyembelih hewan qurban kecuali yang sudah berumur setahun. Apabila kamu sulit mendapatkannya, maka sembelihlah kambing yang berumur enam bulan hingga setahun.â€Â '),
(80, 'Qurban', 'ÙˆÙŽØ¹ÙŽÙ†Ù’ Ø¹ÙŽÙ„ÙÙŠÙÙ‘ Ø¨Ù’Ù†Ù Ø£ÙŽØ¨ÙÙŠ Ø·ÙŽØ§Ù„ÙØ¨Ù Ù‚ÙŽØ§Ù„ÙŽ: { Ø£ÙŽÙ…ÙŽØ±ÙŽÙ†ÙÙŠ Ø§Ù„Ù†Ù‘ÙŽØ¨ÙÙŠÙ‘Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… Ø£ÙŽÙ†Ù‘ÙŽ Ø£ÙŽÙ‚Ù’ÙˆÙŽÙ…ÙŽ Ø¹ÙŽÙ„ÙŽÙ‰ Ø¨ÙØ¯Ù’Ù†ÙÙ‡Ù, ÙˆÙŽØ£ÙŽÙ†Ù’ Ø£ÙÙ‚ÙŽØ³ÙÙ‘Ù…ÙŽ Ù„ÙØ­ÙÙˆÙ…ÙŽÙ‡ÙŽØ§ ÙˆÙŽØ¬ÙÙ„ÙÙˆØ¯ÙŽÙ‡ÙŽØ§ ÙˆÙŽØ¬ÙÙ„Ø§Ù„ÙŽÙ‡ÙŽØ§ Ø¹ÙŽÙ„ÙŽÙ‰ Ø§Ù„Ù’Ù…ÙŽØ³ÙŽØ§ÙƒÙÙŠÙ†Ù, ÙˆÙŽÙ„Ø§ Ø£ÙØ¹Ù’Ø·ÙÙŠÙŽ ÙÙÙŠ Ø¬ÙØ²ÙŽØ§Ø±ÙŽØªÙÙ‡ÙŽØ§ Ù…ÙÙ†Ù’Ù‡ÙŽØ§ Ø´ÙŽÙŠÙ’Ø¦Ø§Ù‹ } Ù…ÙØªÙ‘ÙŽÙÙŽÙ‚ÙŒ Ø¹ÙŽÙ„ÙŽÙŠÙ’Ù‡ ÙÂ ', 'Artinya:â€Rasulullah memerintahkan kepadaku untuk mengurusi hewan qurbannya, membagi-bagikan dagingnya, kulit dan pakaiannya kepada orang-orang miskin, dan aku tidak diperbolehkan memberi sesuatu apapun dari hewan qurban (sebagai upah) kepada penyembelihnya.â€Â '),
(81, 'Qurban', 'ÙˆÙŽØ¹ÙŽÙ†Ù’ Ø¬ÙŽØ§Ø¨ÙØ±Ù Ø¨Ù†Ù Ø¹ÙŽØ¨Ù’Ø¯Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø±ÙŽØ¶ÙÙŠÙŽ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽÙ†Ù’Ù‡ÙÙ…ÙŽØ§ Ù‚ÙŽØ§Ù„ÙŽ: { Ù†ÙŽØ­ÙŽØ±Ù’Ù†ÙŽØ§ Ù…ÙŽØ¹ÙŽ Ø§Ù„Ù†Ù‘ÙŽØ¨ÙÙŠÙÙ‘ ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… Ø¹ÙŽØ§Ù…ÙŽ Ø§Ù„Ù’Ø­ÙØ¯ÙŽÙŠÙ’Ø¨ÙÙŠÙŽØ©Ù: Ø§Ù„Ù’Ø¨ÙŽØ¯ÙŽÙ†ÙŽØ©ÙŽ Ø¹ÙŽÙ†Ù’ Ø³ÙŽØ¨Ù’Ø¹ÙŽØ©Ù, ÙˆÙŽØ§Ù„Ù’Ø¨ÙŽÙ‚ÙŽØ±ÙŽØ©ÙŽ Ø¹ÙŽÙ†Ù’ Ø³ÙŽØ¨Ù’Ø¹ÙŽØ©Ù } Ø±ÙŽÙˆÙŽØ§Ù‡Ù Ù…ÙØ³Ù’Ù„ÙÙ…Â ', 'Artinya:â€Kami pernah menyembelih bersama Rasulullah pada tahun Hudaibiyah dengan seekor unta untuk tujuh orang dan seekor sapi untuk tujuh orang.â€ Â Â '),
(82, 'Qurban', 'Â ÙˆÙŽÙ„ÙŽÙ‡Ù: Ù…ÙÙ†Ù’ Ø­ÙŽØ¯ÙÙŠØ«Ù Ø¹ÙŽØ§Ø¦ÙØ´ÙŽØ©ÙŽ Ø±ÙŽØ¶ÙÙŠÙŽ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽÙ†Ù’Ù‡ÙŽØ§; { Ø£ÙŽÙ…ÙŽØ±ÙŽ Ø¨ÙÙƒÙŽØ¨Ù’Ø´Ù Ø£ÙŽÙ‚Ù’Ø±ÙŽÙ†ÙŽ, ÙŠÙŽØ·ÙŽØ£Ù ÙÙÙŠ Ø³ÙŽÙˆÙŽØ§Ø¯Ù, ÙˆÙŽÙŠÙŽØ¨Ù’Ø±ÙÙƒÙ ÙÙÙŠ Ø³ÙŽÙˆÙŽØ§Ø¯Ù, ÙˆÙŽÙŠÙŽÙ†Ù’Ø¸ÙØ±Ù ÙÙÙŠ Ø³ÙŽÙˆÙŽØ§Ø¯Ù; Ù„ÙÙŠÙØ¶ÙŽØ­ÙÙ‘ÙŠÙŽ Ø¨ÙÙ‡Ù, ÙÙŽÙ‚ÙŽØ§Ù„ÙŽ: \"Ø§ÙØ´Ù’Ø­ÙŽØ°ÙÙŠ Ø§Ù„Ù’Ù…ÙØ¯Ù’ÙŠÙŽØ©ÙŽ\" , Ø«ÙÙ…Ù‘ÙŽ Ø£ÙŽØ®ÙŽØ°ÙŽÙ‡ÙŽØ§, ÙÙŽØ£ÙŽØ¶Ù’Ø¬ÙŽØ¹ÙŽÙ‡Ù, Ø«ÙÙ…Ù‘ÙŽ Ø°ÙŽØ¨ÙŽØ­ÙŽÙ‡Ù, ÙˆÙŽÙ‚ÙŽØ§Ù„ÙŽ: \"Ø¨ÙØ³Ù’Ù…Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù, Ø§ÙŽÙ„Ù„Ù‘ÙŽÙ‡ÙÙ…Ù‘ÙŽ ØªÙŽÙ‚ÙŽØ¨Ù‘ÙŽÙ„Ù’ Ù…ÙÙ†Ù’ Ù…ÙØ­ÙŽÙ…Ù‘ÙŽØ¯Ù ÙˆÙŽØ¢Ù„Ù Ù…ÙØ­ÙŽÙ…Ù‘ÙŽØ¯Ù, ÙˆÙŽÙ…ÙÙ†Ù’ Ø£ÙÙ…Ù‘Ø©Ù Ù…ÙØ­ÙŽÙ…Ù‘ÙŽØ¯Ù', 'Artinya:â€Beliau pernah memerintahkan untuk dibawakan dua ekor kambing kibas bertanduk yang kaki, perut dan sekitar matanya berwarna hitam.Â  Maka dibawakanlah kambing tersebut kepada beliau untuk dijadikan kurban.Â  Beliaupun berkata kepada Aisyah, \"Wahai Aisyah, ambilkan pisau\"Â  Kemudian beliau mengambilnya,Â  membaringkannya dan menyembelihnya seraya berdoa: Bismillaah,Â  alloohumma taqobbal min muhammadin waaali muhammad,Â  wa min ummati muhammad.â€'),
(83, 'Qurban', 'Â Ø£ÙŽÙ†Ù‘ÙŽ Ø¹ÙŽØ§Ø¦ÙØ´ÙŽØ©ÙŽ Ø²ÙŽÙˆÙ’Ø¬ÙŽ Ø§Ù„Ù†Ù‘ÙŽØ¨ÙÙŠÙÙ‘ ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… Ù‚ÙŽØ§Ù„ÙŽØªÙ’: ÙƒÙŽØ§Ù†ÙŽ Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… ÙŠÙÙ‡Ù’Ø¯ÙÙ‰ Ù…ÙÙ†ÙŽ Ø§Ù„Ù’Ù…ÙŽØ¯ÙÙŠÙŽÙ†Ø©Ù. ÙÙŽØ£ÙŽÙÙ’ØªÙÙ„Ù Ù‚ÙŽÙ„Ø§ÙŽØ¦ÙØ¯ÙŽ Ù‡ÙŽØ¯Ù’ÙŠÙÙ‡Ù. Ø«ÙÙ…Ù‘ÙŽ Ù„Ø§ÙŽ ÙŠÙŽØ¬Ù’ØªÙŽÙ†ÙØ¨Ù Ø´ÙŽÙŠÙ’Ø¦Ø§Ù‹ Ù…ÙÙ…Ù‘ÙŽØ§ ÙŠÙŽØ¬Ù’ØªÙŽÙ†ÙØ¨Ù Ø§Ù„Ù’Ù…ÙØ­Ù’Ø±ÙÙ…ÙÂ ', 'Artinya:Rasulullah membawa hewan kurban dari Madinah,Â  lalu beliau menganyam gantungan hewan kurbannya.Â  Beliau tidak menjauhi sesuatu dari hal-hal yang harus dijauhi oleh orang yang berihram.â€'),
(84, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø²ÙŽÙŠÙ’Ø¯Ù Ø¨Ù’Ù†Ù Ø£ÙŽØ±Ù’Ù‚ÙŽÙ…ÙŽ Ù‚ÙŽØ§Ù„ÙŽ Ù‚ÙÙ„Ù’ØªÙ Ø£ÙŽÙˆÙ’ Ù‚ÙŽØ§Ù„ÙÙˆØ§ ÙŠÙŽØ§ Ø±ÙŽØ³ÙÙˆÙ„ÙŽ Ø§Ù„Ù„ÙŽÙ‘Ù‡Ù Ù…ÙŽØ§ Ù‡ÙŽØ°ÙÙ‡Ù Ø§Ù„Ù’Ø£ÙŽØ¶ÙŽØ§Ø­ÙÙŠÙÙ‘ Ù‚ÙŽØ§Ù„ÙŽ Ø³ÙÙ†ÙŽÙ‘Ø©Ù Ø£ÙŽØ¨ÙÙŠÙƒÙÙ…Ù’ Ø¥ÙØ¨Ù’Ø±ÙŽØ§Ù‡ÙÙŠÙ…ÙŽ Ù‚ÙŽØ§Ù„ÙÙˆØ§ Ù…ÙŽØ§ Ù„ÙŽÙ†ÙŽØ§ Ù…ÙÙ†Ù’Ù‡ÙŽØ§ Ù‚ÙŽØ§Ù„ÙŽ Ø¨ÙÙƒÙÙ„ÙÙ‘ Ø´ÙŽØ¹Ù’Ø±ÙŽØ©Ù Ø­ÙŽØ³ÙŽÙ†ÙŽØ©ÙŒ Ù‚ÙŽØ§Ù„ÙÙˆØ§ ÙŠÙŽØ§ Ø±ÙŽØ³ÙÙˆÙ„ÙŽ Ø§Ù„Ù„ÙŽÙ‘Ù‡Ù ÙÙŽØ§Ù„ØµÙÙ‘ÙˆÙÙ Ù‚ÙŽØ§Ù„ÙŽ Ø¨ÙÙƒÙÙ„ÙÙ‘ Ø´ÙŽØ¹Ù’Ø±ÙŽØ©Ù Ù…ÙÙ†Ù’ Ø§Ù„ØµÙÙ‘ÙˆÙÙ Ø­ÙŽØ³ÙŽÙ†ÙŽØ©ÙŒÂ ', 'Artinya:Dari Zaid bin Arqam ia bekata; Saya berkata atau mereka bertanya, â€œWahai Rasulullah, untuk apakah hewan kurban ini?â€ beliau menjawab: â€œYaitu sunnah bapak kalian Ibrahim.â€ Mereka bertanya lagi, â€œLalu kebaikan apakah yang akan kami peroleh darinya?â€ beliau menjawab: â€œSetiap helai dari bulunya adalah kebaikan.â€ Mereka bertanya lagi, â€œBagaimana dengan domba?â€ beliau menjawab: â€œSetiap helai bulu domba itu adalah bernilai satu kebaikan.â€ (HR. Ahmad, Ibnu Majah, Al-Hakim,)'),
(85, 'Qurban', 'Â Ø¹ÙŽÙ†Ù’ Ø¬ÙŽØ§Ø¨ÙØ±Ù Ø¨Ù’Ù†Ù Ø¹ÙŽØ¨Ù’Ø¯Ù Ø§Ù„Ù„Ù‡Ù Ù‚ÙŽØ§Ù„ÙŽ: Ø´ÙŽÙ‡ÙØ¯Ù’ØªÙ Ù…ÙŽØ¹ÙŽ Ø±ÙŽØ³ÙÙˆÙ’Ù„Ù Ø§Ù„Ù„Ù‡Ù Øµ Ø§Ù’Ù„Ø§ÙŽØ¶Ù’Ø­ÙŽÙ‰ Ø¨ÙØ§Ù’Ù„Ù…ÙØµÙŽÙ„Ù‘ÙŽÙ‰. ÙÙŽÙ„ÙŽÙ…Ù‘ÙŽØ§ Ù‚ÙŽØ¶ÙŽÙ‰ Ø®ÙØ·Ù’Ø¨ÙŽØªÙŽÙ‡Ù Ù†ÙŽØ²ÙŽÙ„ÙŽ Ù…ÙÙ†Ù’ Ù…ÙÙ†Ù’Ø¨ÙŽØ±ÙÙ‡Ù ÙˆÙŽ Ø§ÙØªÙÙŠÙŽ Ø¨ÙÙƒÙŽØ¨Ù’Ø´Ù ÙÙŽØ°ÙŽØ¨ÙŽØ­ÙŽÙ‡Ù Ø±ÙŽØ³ÙÙˆÙ’Ù„Ù Ø§Ù„Ù„Ù‡Ù Øµ Ø¨ÙÙŠÙŽØ¯ÙÙ‡Ù ÙˆÙŽ Ù‚ÙŽØ§Ù„ÙŽ: Ø¨ÙØ³Ù’Ù…Ù Ø§Ù„Ù„Ù‡Ù ÙˆÙŽ Ø§Ù„Ù„Ù‡Ù Ø§ÙŽÙƒÙ’Ø¨ÙŽØ±ÙØŒ Ù‡Ø°ÙŽØ§ Ø¹ÙŽÙ†Ù‘Ù‰ ÙˆÙŽ Ø¹ÙŽÙ…Ù‘ÙŽÙ†Ù’ Ù„ÙŽÙ…Ù’ ÙŠÙØ¶ÙŽØ­Ù‘ Ù…ÙÙ†Ù’ Ø§ÙÙ…Ù‘ÙŽØªÙÙ‰. Ø§Ø¨Ùˆ Ø¯Ø§ÙˆØ¯ 3: 99ØŒ Ø±Ù‚Ù…:2810Â ', 'Artinya:Dari Jabir bin Abdullah, ia berkata : Aku shalat Iedul Adlha bersama Rasulullah SAW di mushalla. Setelah beliau selesai berkhutbah, lalu turun dari mimbar, maka didatangkan seekor kibasy, lalu beliau menyembelihnya dengan tangan beliau, dan beliau mengucapkan, â€œBismillaahi walloohu Akbar, haadzaaannii wa amman lam yudlohhi min ummatii (Dengan nama Allah dan Allah Maha Besar. (Qurban) ini dariku dan dari ummatku yang tidak berqurban)â€. [HR. Abu Dawud juz 3, hal. 99, no. 2810]'),
(86, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø¬ÙŽØ§Ø¨ÙØ±Ù Ø¨Ù’Ù†Ù Ø¹ÙŽØ¨Ù’Ø¯Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ù‚ÙŽØ§Ù„ÙŽ Ø´ÙŽÙ‡ÙØ¯Ù’ØªÙ Ù…ÙŽØ¹ÙŽ Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù -ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù…- Ø§Ù„Ø£ÙŽØ¶Ù’Ø­ÙŽÙ‰ Ø¨ÙØ§Ù„Ù’Ù…ÙØµÙŽÙ„Ù‘ÙŽÙ‰ ÙÙŽÙ„ÙŽÙ…Ù‘ÙŽØ§ Ù‚ÙŽØ¶ÙŽÙ‰ Ø®ÙØ·Ù’Ø¨ÙŽØªÙŽÙ‡Ù Ù†ÙŽØ²ÙŽÙ„ÙŽ Ù…ÙÙ†Ù’ Ù…ÙÙ†Ù’Ø¨ÙŽØ±ÙÙ‡Ù ÙˆÙŽØ£ÙØªÙÙ‰ÙŽ Ø¨ÙÙƒÙŽØ¨Ù’Ø´Ù ÙÙŽØ°ÙŽØ¨ÙŽØ­ÙŽÙ‡Ù Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù -ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù…- Ø¨ÙÙŠÙŽØ¯ÙÙ‡Ù ÙˆÙŽÙ‚ÙŽØ§Ù„ÙŽ: (( Ø¨ÙØ³Ù’Ù…Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù ÙˆÙŽØ§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø£ÙŽÙƒÙ’Ø¨ÙŽØ±Ù Ù‡ÙŽØ°ÙŽØ§ Ø¹ÙŽÙ†Ù‘ÙÙ‰ ÙˆÙŽØ¹ÙŽÙ…Ù‘ÙŽÙ†Ù’ Ù„ÙŽÙ…Ù’ ÙŠÙØ¶ÙŽØ­Ù‘Ù Ù…ÙÙ†Ù’ Ø£ÙÙ…Ù‘ÙŽØªÙÙ‰ )).', 'Artinya:â€œDiriwayatkan dari Jabir bin Abdillah radhiallahu anhu bahwasanya dia berkata, â€œSaya menghadiri shalat idul-Adha bersama Rasulullah shallallahu alaihi wa sallam di mushalla (tanah lapang). Setelah beliau berkhutbah, beliau turun dari mimbarnya dan didatangkan kepadanya seekor kambing. Kemudian Rasulullah shallallahu alaihi wa sallam menyembelihnya dengan tangannya, sambil mengatakan: Dengan nama Allah. Allah Maha Besar. Kambing ini dariku dan dari orang-orang yang belum menyembelih di kalangan umatkuâ€Â '),
(87, 'Qurban', '( Ù…ÙŽÙ†Ù’ ÙˆÙŽØ¬ÙŽØ¯ÙŽ Ø³ÙŽØ¹ÙŽØ©Ù‹ ÙÙŽÙ„ÙŽÙ…Ù’ ÙŠÙØ¶ÙŽØ­ÙÙ‘ ÙÙŽÙ„Ø§ ÙŠÙŽÙ‚Ù’Ø±ÙŽØ¨ÙŽÙ†ÙŽÙ‘ Ù…ÙØµÙŽÙ„Ø§ÙŽÙ‘Ù†ÙŽØ§. ))Â ', 'Artinya:â€œBarang siapa mendapatkan kelapangan tetapi tidak berqurban, maka janganlah dia mendekati tempat shalat kami.\"'),
(88, 'Qurban', 'Â Ø¹ÙŽÙ†Ù’ Ø´ÙŽØ¯Ù‘ÙŽØ§Ø¯Ù Ø¨Ù’Ù†Ù Ø§ÙŽÙˆÙ’Ø³Ù Ù‚ÙŽØ§Ù„ÙŽ: Ø«ÙÙ†Ù’ØªÙŽØ§Ù†Ù Ø­ÙŽÙÙØ¸Ù’ØªÙÙ‡ÙÙ…ÙŽØ§ Ù…ÙÙ†Ù’ Ø±ÙŽØ³ÙÙˆÙ’Ù„Ù Ø§Ù„Ù„Ù‡Ù Øµ. Ù‚ÙŽØ§Ù„ÙŽ: Ø§ÙÙ†Ù‘ÙŽ Ø§Ù„Ù„Ù‡ÙŽ ÙƒÙŽØªÙŽØ¨ÙŽ Ø§Ù’Ù„Ø§ÙØ­Ù’Ø³ÙŽØ§Ù†ÙŽ Ø¹ÙŽÙ„ÙŽÙ‰ ÙƒÙÙ„Ù‘ Ø´ÙŽÙŠÙ’Ø¡Ù. ÙÙŽØ§ÙØ°ÙŽØ§ Ù‚ÙŽØªÙŽÙ„Ù’ØªÙÙ…Ù’ ÙÙŽØ§ÙŽØ­Ù’Ø³ÙÙ†ÙÙˆØ§ Ø§Ù’Ù„Ù‚ÙØªÙ’Ù„ÙŽØ©ÙŽ ÙˆÙŽ Ø§ÙØ°ÙŽØ§ Ø°ÙŽØ¨ÙŽØ­Ù’ØªÙÙ…Ù’ ÙÙŽØ§ÙŽØ­Ù’Ø³ÙÙ†ÙÙˆØ§ Ø§Ù„Ø°Ù‘ÙŽØ¨Ù’Ø­ÙŽ ÙˆÙŽ Ù„Ù’ÙŠÙØ­ÙØ¯Ù‘ÙŽ Ø§ÙŽØ­ÙŽØ¯ÙÙƒÙÙ…Ù’ Ø´ÙŽÙÙ’Ø±ÙŽØªÙŽÙ‡Ù ÙÙŽÙ„Ù’ÙŠÙØ±ÙØ­Ù’ Ø°ÙŽØ¨ÙÙŠÙ’Ø­ÙŽØªÙŽÙ‡Ù. Ù…Ø³Ù„Ù… 3: 1548', 'Artinya:Dari Syaddad bin Aus, ia berkata : Dua hal yang aku hafal dari Rasulullah SAW, beliau bersabda, â€œSesungguhnya Allah mewajibkan berbuat baik pada segala sesuatu. Maka apabila kalian membunuh, bunuhlah dengan baik. Dan apabila kalian menyembelih, sembelihlah dengan baik, hendaklah salah seorang diantara kalian menajamkan pisaunya, dan mudahkanlah penyembelihannyaâ€. [HR. Muslim juz 3, hal. 1548]'),
(89, 'Qurban', 'Ù†Ù’ ÙŽØ£Ù†ÙŽØ³Ù Ù‚Ø§Ù„ : Ø¶ÙØ­ÙŽÙ‰ Ø§Ù„Ù†ÙŽÙ‘Ø¨ÙÙ‰ÙÙ‘ ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… Ø¨ÙÙƒØ¨Ù’Ø´ÙŽÙŠÙ’Ù†Ù ÙŽØ£Ù‚Ù’Ø±ÙŽÙ†ÙŽÙŠÙ’Ù†Ù ÙŽØ°Ø¨ÙŽØ­ÙŽÙ‡ÙÙ…ÙŽØ§ Ø¨ÙÙŠÙŽØ¯ÙÙ‡Ù ÙˆÙŽØ³ÙŽÙ…ÙŽÙ‘Ù‰ ÙˆÙŽ ÙƒØ¨ÙŽÙ‘Ø±ÙŽ (Ø±ÙˆØ§Ù‡ Ø§Ù„Ø¨Ø®Ø§Ø±ÙŠ ÙˆÙ…Ø³Ù„Ù…)', 'Artinya:â€Dari Anas berkata : â€œBahwasannya Nabi SAW telah berkurban dengan dua ekor kibas yang enak dipandang mata lagi mempunyai tanduk. Beliau menyembelih sendiri dengan membaca basmalah dan mengucapkan takbirâ€ (HR. al-Bukhari dan Muslim).'),
(90, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø¬ÙŽØ§Ø¨ÙØ±Ù Ù‚Ø§Ù„: Ù‚Ø§Ù„ Ø±ÙŽØ³ÙÙˆÙ’Ù„Ù Ø§Ù„Ù„Ù‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù…: ÙŽÙ„Ø§ØªÙŽØ°Ø¨ÙŽØ­ÙÙˆÙ’Ø§ Ø¥ÙÙ„ÙŽÙ‘Ø§Ù…ÙØ³ÙÙ†ÙŽÙ‘Ø© Ø§ÙÙ„ÙŽÙ‘Ø§ ÙŽØ£Ù† ÙŠÙŽÙ‘Ø¹Ù’Ø³ÙØ±ÙŽ Ø¹ÙŽÙ„ÙŠÙ’ÙƒÙ…Ù’ ÙÙŽØªÙŽØ°Ù’Ø¨ÙŽØ­ÙÙˆÙ’Ø§ Ø¬ÙŽØ°Ø¹ÙŽØ© Ù…ÙÙ†ÙŽ Ø§Ù„Ø¶ÙŽÙ‘Ø£Ù’Ù†Ù (Ø±ÙˆØ§Ù‡ Ø§Ù„Ø¬Ù…Ø§Ø¹Ø© Ø§Ù„Ø§ Ø§Ù„Ø¨Ø®Ø§Ø±ÙŠ)', 'Artinya:â€œDari Jabir berkata: bersabda Rasulullah SAW janganlah kamu menyembelih untuk kurban melainkan yang â€œmusinahâ€ (berumur dua tahun), jika kamu sukar memeperolehnya maka sembelihlahÂ hewan yang berumur satu tahunâ€. ( HR. Jamaâ€™ah selain Bukhari)'),
(91, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø¹ÙÙ‚Ù’Ø¨ÙŽØ© Ø¨Ù’Ù†Ù Ø¹ÙŽØ§ÙÙ…ÙØ± Ø§Ù„Ø¬ÙÙ‡ÙŽÙ†ÙÙ‰ÙŽÙ‘ Ù‚Ø§Ù„: ÙŽÙ‚Ø³ÙŽÙ…ÙŽ Ø±ÙŽØ³ÙÙˆÙ’Ù„Ù Ø§Ù„Ù„Ù‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… ÙÙÙŠÙ’Ù†ÙŽØ§ Ø¶ÙŽØ­ÙŽØ§ÙŠÙŽØ§ ÙÙŽØ£ØµÙŽØ§Ø¨ÙŽÙ†ÙÙ‰ Ø¬ÙŽØ°Ø¹ÙŒ ÙŽÙÙ‚ÙÙ„Ù’ØªÙ: ÙŠÙŽØ§Ø±ÙŽØ³ÙÙˆÙ’Ù„ Ø§Ù„Ù„Ù‡Ù Ø¥ÙÙ†ÙŽÙ‡Ù Ø£ØµÙŽØ§Ø¨ÙŽÙ†ÙÙ‰ Ø¬ÙŽØ°Ø¹ÙŒ ÙÙŽÙ‚ÙŽØ§Ù„ Ø¶ÙŽØ­ÙŽÙ‘ Ø¨ÙÙ‡Ù (Ø±ÙˆØ§Ù‡ Ø§Ù„Ø¨Ø®Ø§Ø±Ù‰ ÙˆÙ…Ø³Ù„Ù… )', 'Artinya:â€Dari Uqbah ibn Amir al-Juhani berkata : Rasulullah SAW membagi kepada kami hewan kurban, maka saya memperoleh anak kambing, saya berkata, Ya Rasulullah saya hanya memperoleh anak kambing, Rasulullah menjawab, berkurbanlah dengan anak kambing ituâ€œ. (HR. Bukhari Muslim)'),
(92, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø¬ÙŽØ¨ÙÙŠÙ’Ø±Ù Ø¨Ù’Ù†Ù Ù…ÙŽØ·Ø¹ÙŽÙ…Ù’ Ù‚ÙŽØ§Ù„ Ø§Ù„Ù†Ø¨ÙŠ ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… Â ÙƒÙ„Ù‘ Ø£ÙŠÙŽÙ‘Ø§Ù…Ù Ø§Ù„ØªÙŽÙ‘Ø´Ù’Ø±ÙÙŠÙ’Ù‚Ù Ø°ÙŽØ¨Ù’Ø­ÙŒ (Ø±ÙˆØ§Ù‡ Ø§Ø­Ù…Ø¯)', 'Artinya:â€œDari Jubair bin Muthâ€™im berkata. Bersabda Nabi SAW seluruh hari Tasyriq merupakan waktu penyembelihanâ€. (HR. Ahmad)'),
(93, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø¬ÙÙ†Ù’Ø¯ÙŽ Ø¨Ù’Ù†Ù Ø³ÙÙÙ’ÙŠÙŽØ§Ù†Ù Ù’Ø§Ù„Ø¨ÙŽØ¬ÙŽÙ„ÙÙŠ Ù‚Ø§Ù„: Ø´ÙŽÙ‡Ø¯Ù’ØªÙ Ø§Ù„Ù†ÙŽÙ‘Ø¨ÙŠ ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… ÙŠÙŽÙˆÙ’Ù…ÙŽ Ø§Ù„Ù†ÙŽÙ‘Ø­Ù’Ø±Ù ÙÙ‚Ø§Ù„: Ù…ÙŽÙ†Ù’ ÙŽØ°Ø¨ÙŽØ­ÙŽ ÙŽÙ‚Ø¨Ù’Ù„ ÙŽØ£Ù† ÙŠÙØµÙŽÙ„ÙÙ‘Ù‰ÙŽ ÙÙ„Ù’ÙŠÙØ¹ÙØ¯Ù’ Ù…ÙŽÙƒÙŽØ§Ù† Ø£Ø®ÙŽØ±ÙŽ ÙˆÙŽÙ…ÙŽÙ†Ù’ ÙŽÙ„Ù…Ù’ ÙŠÙŽØ°Ø¨ÙŽØ­Ù’ ÙÙ„Ù’ÙŠÙŽØ°Ù’Ø¨ÙŽØ­ (Ø±ÙˆØ§Ù‡ Ø§Ù„Ø¨Ø®Ø§Ø±ÙŠ)', 'Artinya:â€Dari Jundab bin Sufyan al-Bajali, dia berkata â€œAku menyaksikan Nabi SAW, pada hari kurban. Beliau bersabda â€œ Barang siapa yang menyembelih kurban sebelum dia melakukan sembahyang Idul Adha, maka ia hendaknya mengulang. Dan barang siapa yang belum nemyembelih hendaklah dia lakukanâ€œ. (HR. Bukhori)'),
(94, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø¬ÙŽØ§Ø¨ÙØ±Ù Ø¨Ù’Ù†Ù Ø¹ÙŽØ¨Ù’Ø¯ Ø§Ù„Ù„Ù‡Ù Ø£Ù†ÙŽÙ‘Ù‡Ù Ù‚Ø§Ù„: Ù†ÙŽØ­ÙŽØ±Ù’Ù†ÙŽØ§ Ù…ÙŽØ¹ÙŽ Ø±ÙŽØ³ÙÙˆÙ’Ù„Ù Ø§Ù„Ù„Ù‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… Ø¨ÙØ§Ù„Ù’Ø­ÙØ¯ÙŽÙŠÙ’Ø¨ÙÙŠÙŽØ©Ù Ø§Ù„Ù’Ø¨ÙŽØ¯ÙŽÙ†ÙŽØ© Ø¹ÙŽÙ†Ù’ Ø³ÙŽØ¨Ù’Ø¹ÙŽØ©Ù ÙˆÙŽØ§Ù„Ø¨ÙŽÙ‚Ø±ÙŽØ© Ø¹ÙŽÙ†Ù’ Ø³ÙŽØ¨Ù’Ø¹ÙŽØ©Ù (Ø±ÙˆØ§Ù‡ Ù…Ø³Ù„Ù… ÙˆØ§Ù„ØªØ±Ù…Ø°ÙŠ ÙˆØ£Ø¨ÙˆØ¯Ø§ÙˆØ¯)', 'Artinya:â€œDari Jabir ibn Abdullah berkata : pada tahun perjanjian Hudaibiyah kami menyembelih kurban bersama Nabi SAW unta untuk tujuh orang dan sap juga untuk tujuh orangâ€œ. ( HR. Muslim, at-Tirmidzi dan Abu Dawud)'),
(95, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø¹ÙŽØ§Ø¦ÙØ´ÙŽØ© Ø±ÙŽØ¶ÙÙŠ Ø§Ù„Ù„Ù‡ Ø¹ÙŽÙ†Ù’Ù‡ÙŽØ§ Ù‚Ø§Ù„Øª Ø¯ÙŽÙÙŽÙ‘ Ø§Ù„Ù†ÙŽÙ‘Ø§Ø³ Ù…ÙÙ†Ù’ ÙŽØ£Ù‡Ù’Ù„Ù Ù’Ø§Ù„Ø¨ÙŽØ§Ø¯ÙÙŠÙŽØ© Ø­ÙŽØ¶Ù’Ø±ÙŽØ©Ù Ù’Ø§Ù„Ø£ÙŽØ¶Ù’Ø­ÙŽÙ‰ ÙÙÙŠ Ø²ÙŽÙ…ÙŽØ§ÙÙ† Ø±ÙŽØ³ÙÙˆÙ’Ù„Ù Ø§Ù„Ù„Ù‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… ÙÙ‚Ø§Ù„ Ø±Ø³ÙˆÙ„ Ø§Ù„Ù„Ù‡ ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… ÙŽØ§Ø¯Ù’Ø®ÙØ±ÙÙˆØ§ Ø§ Ù„Ø«ÙÙ„Ø« ÙˆÙŽØªÙŽØµÙŽØ¯ÙŽÙ‘Ù‚ÙˆÙ’Ø§ Ø¨ÙÙ…ÙŽØ§ Ø¨ÙŽÙ‚ÙÙŠ (Ø±ÙˆØ§Ù‡ Ø§Ø¨Ùˆ Ø¯Ø§ÙˆØ¯)', 'Artinya:â€Dari Aisyah Ra berkat : pernah manusia penduduk desa berduyunduyun untuk menghadiri kurban di masa Rasulullah SAW. Maka bersabda Rasulullah SAW â€œsimpanlah sepertiga daging itu, dan sedekahkahnlah yang lainnyaâ€ (HR. Abu Daud).'),
(96, 'Qurban', 'Ø¹Ù† Ø¹Ù„ÙŠ Ù‚Ø§Ù„ : Ø£Ù…ÙŽØ±ÙŽÙ†ÙÙŠ Ø±Ø³Ùˆ Ù„ Ø§Ù„Ù„Ù‡ ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… Ø£Ù† ÙŽØ£Ù‚ÙÙˆÙ’Ù…ÙŽ Ø¹ÙŽÙ„Ù‰ Ø¨Ø¯Ù’Ù†ÙÙ‡Ù ÙˆÙŽØ£Ù†Ù’ ÙŽØ£ØªÙŽØµÙŽØ¯ÙŽÙ‘Ù‚ÙŽ Ø¨ÙÙ„ÙŽØ­Ù’Ù…ÙÙ‡ÙŽØ§ ÙˆÙŽØ¬ÙÙ„ÙÙˆÙ’Ø¯ÙÙ‡ÙŽØ§ ÙˆÙŽØ§Ø¬ÙÙ„ÙŽØªÙÙ‡ÙŽØ§ ÙˆÙŽØ£Ù†Ù’ Ù„ÙŽØ§Ø£ÙØ¹Ù’Ø·ÙÙŠ Ø§Ù„Ù’Ø¬ÙŽØ²ÙŽÙ‘Ø§Ø±ÙŽ Ù…ÙÙ†Ù’Ù‡ÙŽØ§ Ù‚ÙŽØ§Ù„: â€œÙ†ÙŽØ­Ù’Ù†Ù Ù†ÙØ¹Ù’Ø·ÙÙŠÙ’Ù‡Ù Ù…ÙÙ†Ù’ Ø¹ÙÙ†Ù’Ø¯ÙÙ†ÙŽØ§ â€ (Ù…ØªÙÙ‚ Ø¹Ù„ÙŠÙ‡)', 'Artinya:â€Dari sahabat Ali RA. Berkata : Rasulullah SAW menyuruhku untuk menangani unta kurban dan membagikan kulit dan penutup tubuhnya (kain yang dipakaikan pada hewan kurban), serta melarangku memberikan kepada si penjagal sesuatu dari padanya. Beliau berkata â€œkita memberi dia upah dari kita sendiriâ€. (HR. Muttafaq â€™alaih)'),
(97, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø³ÙŽÙ„Ù…ÙŽØ© Ø¨Ù†Ù Ø§Ù„Ø£ÙŽÙƒÙ’ÙˆÙŽØ¹Ù Ù‚Ø§Ù„: Ù‚Ø§Ù„ Ø±Ø³ÙˆÙ„ Ø§Ù„Ù„Ù‡ ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù…: Ù…ÙŽÙ†Ù’ Ø¶ÙŽØ­ÙŽÙ‘Ù‰ Ù…ÙÙ†Ù’ÙƒÙ…Ù’ ÙŽÙÙ„Ø§ ÙŠÙØµÙ’Ø¨ÙØ­ÙŽÙ†ÙŽÙ‘ Ø¨ÙŽØ¹Ù’Ø¯ÙŽ Ø«Ø§Ù„ÙŽØ«Ø©Ù ÙˆÙŽÙÙÙŠÙ’ Ø¨ÙŽÙŠÙ’ØªÙÙ‡Ù Ù…ÙÙ†Ù’Ù‡Ù Ø´ÙŽÙŠÙ’ ÙŒ ÙŽÙÙŽÙ„Ù…ÙŽÙ‘Ø§ÙƒÙŽØ§Ù† Ø§Ù„Ø¹ÙŽØ§Ù…Ù Ø§Ù„Ù…ÙÙ‚Ù’Ø¨ÙÙ„Ù Ù‚Ø§ÙÙ„ÙˆÙ’Ø§ : ÙŠÙŽØ§Ø±ÙŽØ³ÙÙˆÙ’Ù„ Ø§Ù„Ù„Ù‡Ù Ù†ÙŽÙÙ’Ø¹ÙŽÙ„Ù ÙƒÙ…ÙŽØ§ ÙÙŽØ¹ÙŽÙ„Ù’Ù†ÙŽØ§ Ø§Ù„Ø¹ÙŽØ§Ù…ÙŽ Ø§Ù„Ù’Ù…ÙŽØ§Ø¶ Ù‚Ø§Ù„: ÙƒÙÙ„ÙˆÙ’Ø§ ÙˆÙŽØ£Ø·Ø¹ÙÙ…ÙÙˆÙ’Ø§ ÙˆÙŽØ£Ø¯ÙŽÙ‘Ø®ÙØ±ÙÙˆÙ’Ø§ ÙŽÙØ£ÙÙ†ÙŽÙ‘ ÙŽØ°Ù„ÙÙƒÙŽ Ù’Ø§Ù„Ø¹ÙŽØ§Ù…ÙŽ ÙƒÙŽØ§Ù† Ø¨ÙØ§Ù„Ù†ÙŽÙ‘Ø§Ø³Ù Ø¬ÙŽÙ‡Ù’Ø¯ÙŒ ÙÙŽØ£Ø±ÙŽØ¯Ù’ØªÙ Ø£Ù† ØªÙØ¹ÙÙŠÙ’Ù†ÙÙˆÙ’Ø§ ÙÙÙŠÙ’Ù‡ÙŽØ§ (Ù…ØªÙÙ‚ Ø¹Ù„ÙŠÙ‡)', 'Artinya:â€Dari Salamah Ibn al-Akwa berkata : Nabi SAW bersabda barang siapa diantara kamu sekalian berkurban maka janganlah. Menyimpan sesuatu pun (dari daging kurban) setelah tiga hari. Kemudian pada tahun berikutnya para sahabat bertanya : Wahai Rasulullah apakah kami melakukan seperti tahun lalu? Rasulullah bersabda â€makanlah (dari kurban mu), dan berilah orang-orang, dan simpanlah, sesungguhnya pada tahun yang lalu itu orang-orang mendapat kesusahan, maka aku ingin kamu menolong merekaâ€. (Muttafaq â€˜Alah)'),
(98, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø£ÙŽØ¨ÙÙŠ Ø·ÙŽÙ„Ù’Ø­ÙŽØ©ÙŽ â€œØ£ÙŽÙ†Ù‘ÙŽ Ø§Ù„Ù†Ù‘ÙŽØ¨ÙÙŠ ØµÙŽÙ„Ù‘ÙŽÙ‰ Ø§Ù„Ù„Ù‡Ù Ø¹ÙŽÙ„ÙŽÙŠÙ’Ù‡Ù ÙˆÙŽØ³ÙŽÙ„Ù‘ÙŽÙ…ÙŽ Ø¶ÙŽØ­Ù‘ÙŽÙ‰ Ø¨ÙÙƒÙŽØ¨Ù’Ø´ÙŽÙŠÙ’Ù†Ù Ø£ÙŽÙ…Ù’Ù„ÙŽØ­ÙŽÙŠÙ’Ù†Ù ÙÙŽÙ‚ÙŽØ§ÙŽÙ„ÙŽ Ø¹ÙÙ†Ù’Ø¯ÙŽ Ø§Ù„Ø£ÙŽÙˆÙ‘ÙŽÙ„Ù Ø¹ÙŽÙ†Ù’ Ù…ÙØ­ÙŽÙ…Ù‘ÙŽØ¯Ù ÙˆÙŽØ¢Ù„Ù Ù…ÙØ­ÙŽÙ…Ù‘ÙŽØ¯ÙØŒ ÙˆÙŽØ¹ÙÙ†Ù’Ø¯ÙŽ Ø§Ù„Ø«Ù‘ÙŽØ§Ù†ÙÙŠ Ø¹ÙŽÙ…Ù‘ÙŽÙ†Ù’ Ø¢Ù…ÙŽÙ†ÙŽ Ø¨ÙÙŠ ÙˆÙŽØµÙŽØ¯Ù‘ÙŽÙ‚ÙŽÙ†ÙÙŠ Ù…ÙÙ†Ù’ Ø£ÙÙ…Ù‘ÙŽØªÙÙŠ', 'Artinya:Diriwayatkan dari Abu Thalhah Radhiyallahu anh, bahwa Nabi Shallallahu alaihi wa sallam menyembelih dua ekor kambing kibasy yang berwarna putih. Ketika menyembelih kambing yang pertama, Beliau berkata: â€œDari Muhammad dan keluarga Muhammad.â€ Dan ketika menyembelih yang kedua, Beliau berkata: â€œDari siapa saja yang beriman kepadaku dan membenarkanku dari kalangan umatku.â€ [Diriwayatkan oleh Ibnu Abi Syaibah dan Mushannaf dan Abu Yaâ€™laa Al Muushili dalam Musnad-nya].'),
(99, 'Qurban', 'ÙˆÙŽØ¹ÙŽÙ†Ù’ Ø¬ÙÙ†Ù’Ø¯ÙØ¨Ù Ø¨Ù’Ù†Ù Ø³ÙÙÙ’ÙŠÙŽØ§Ù†ÙŽ Ù‚ÙŽØ§Ù„ÙŽ: { Ø´ÙŽÙ‡ÙØ¯Ù’ØªÙ Ø§Ù„Ø£ÙŽØ¶Ù’Ø­ÙŽÙ‰ Ù…ÙŽØ¹ÙŽ Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… ÙÙŽÙ„ÙŽÙ…Ù‘ÙŽØ§ Ù‚ÙŽØ¶ÙŽÙ‰ ØµÙŽÙ„Ø§ØªÙŽÙ‡Ù Ø¨ÙØ§Ù„Ù†Ù‘ÙŽØ§Ø³Ù, Ù†ÙŽØ¸ÙŽØ±ÙŽ Ø¥ÙÙ„ÙŽÙ‰ ØºÙŽÙ†ÙŽÙ…Ù Ù‚ÙŽØ¯Ù’ Ø°ÙØ¨ÙØ­ÙŽØªÙ’, ÙÙŽÙ‚ÙŽØ§Ù„ÙŽ: \"Ù…ÙŽÙ†Ù’ Ø°ÙŽØ¨ÙŽØ­ÙŽ Ù‚ÙŽØ¨Ù’Ù„ÙŽ Ø§Ù„ØµÙ‘ÙŽÙ„Ø§Ø©Ù ÙÙŽÙ„Ù’ÙŠÙŽØ°Ù’Ø¨ÙŽØ­Ù’ Ø´ÙŽØ§Ø©Ù‹ Ù…ÙŽÙƒÙŽØ§Ù†ÙŽÙ‡ÙŽØ§, ÙˆÙŽÙ…ÙŽÙ†Ù’ Ù„ÙŽÙ…Ù’ ÙŠÙŽÙƒÙÙ†Ù’ Ø°ÙŽØ¨ÙŽØ­ÙŽ ÙÙŽÙ„Ù’ÙŠÙŽØ°Ù’Ø¨ÙŽØ­Ù’ Ø¹ÙŽÙ„ÙŽÙ‰ Ø§Ø³Ù’Ù…Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù\" } Ù…ÙØªÙ‘ÙŽÙÙŽÙ‚ÙŒ Ø¹ÙŽÙ„ÙŽÙŠÙ’Ù‡ Ù', 'Artinya:â€Barangsiapa menyembelih sebelum shalat, hendaknya ia menyembelih seekor kambing lagi sebagai gantinya. Barangsiapa belum menyembelih, hendaknya ia menyembelih dengan nama Allah.â€'),
(100, 'Qurban', 'ÙˆÙŽØ¹ÙŽÙ†Ù’ Ø¬ÙŽØ§Ø¨ÙØ±Ù Ø¨Ù†Ù Ø¹ÙŽØ¨Ù’Ø¯Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø±ÙŽØ¶ÙÙŠÙŽ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽÙ†Ù’Ù‡ÙÙ…ÙŽØ§ Ù‚ÙŽØ§Ù„ÙŽ: { Ù†ÙŽØ­ÙŽØ±Ù’Ù†ÙŽØ§ Ù…ÙŽØ¹ÙŽ Ø§Ù„Ù†Ù‘ÙŽØ¨ÙÙŠÙÙ‘ ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù… Ø¹ÙŽØ§Ù…ÙŽ Ø§Ù„Ù’Ø­ÙØ¯ÙŽÙŠÙ’Ø¨ÙÙŠÙŽØ©Ù: Ø§Ù„Ù’Ø¨ÙŽØ¯ÙŽÙ†ÙŽØ©ÙŽ Ø¹ÙŽÙ†Ù’ Ø³ÙŽØ¨Ù’Ø¹ÙŽØ©Ù, ÙˆÙŽØ§Ù„Ù’Ø¨ÙŽÙ‚ÙŽØ±ÙŽØ©ÙŽ Ø¹ÙŽÙ†Ù’ Ø³ÙŽØ¨Ù’Ø¹ÙŽØ©Ù } Ø±ÙŽÙˆÙŽØ§Ù‡Ù Ù…ÙØ³Ù’Ù„ÙÙ…', 'Artinya:â€Kami pernah menyembelih bersama Rasulullah pada tahun Hudaibiyah dengan seekor unta untuk tujuh orang dan seekor sapi untuk tujuh orang.â€'),
(101, 'Qurban', 'Ø£ÙŽÙ…ÙŽØ±ÙŽÙ†ÙŽØ§ Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù ØµÙŽÙ„Ù‘ÙŽÙ‰ Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø¹ÙŽÙ„ÙŽÙŠÙ’Ù‡Ù ÙˆÙŽØ³ÙŽÙ„Ù‘ÙŽÙ…ÙŽ Ø£ÙŽÙ†Ù’ Ù†ÙŽØ´Ù’ØªÙŽØ±ÙÙƒÙŽ ÙÙÙŠ Ø§Ù„Ø¥ÙØ¨ÙÙ„Ù ÙˆÙŽØ§Ù„Ù’Ø¨ÙŽÙ‚ÙŽØ±Ù ÙƒÙÙ„Ù‘ÙŽ Ø³ÙŽØ¨ÙŽØ¹ÙŽØ©Ù Ù…ÙÙ†Ù‘ÙŽØ§ ÙÙÙŠ Ø¨ÙŽØ¯ÙŽÙ†ÙŽØ©Ù', 'Artinya:â€œRasulullah Shallallahu Alaihi Wasallam memerintahkan kami patungan pada sesekor unta dan sapi. Setiap 7 orang dari kami berserikat dalam satu ekor.â€ (HR. Muslim)'),
(102, 'Qurban', 'Ø¹ÙŽÙ†Ù’ Ø¬ÙŽØ§Ø¨ÙØ±Ù Ø¨Ù’Ù†Ù Ø¹ÙŽØ¨Ù’Ø¯Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù Ù‚ÙŽØ§Ù„ÙŽ Ø´ÙŽÙ‡ÙØ¯Ù’ØªÙ Ù…ÙŽØ¹ÙŽ Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù -ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù…- Ø§Ù„Ø£ÙŽØ¶Ù’Ø­ÙŽÙ‰ Ø¨ÙØ§Ù„Ù’Ù…ÙØµÙŽÙ„Ù‘ÙŽÙ‰ ÙÙŽÙ„ÙŽÙ…Ù‘ÙŽØ§ Ù‚ÙŽØ¶ÙŽÙ‰ Ø®ÙØ·Ù’Ø¨ÙŽØªÙŽÙ‡Ù Ù†ÙŽØ²ÙŽÙ„ÙŽ Ù…ÙÙ†Ù’ Ù…ÙÙ†Ù’Ø¨ÙŽØ±ÙÙ‡Ù ÙˆÙŽØ£ÙØªÙÙ‰ÙŽ Ø¨ÙÙƒÙŽØ¨Ù’Ø´Ù ÙÙŽØ°ÙŽØ¨ÙŽØ­ÙŽÙ‡Ù Ø±ÙŽØ³ÙÙˆÙ„Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù -ØµÙ„Ù‰ Ø§Ù„Ù„Ù‡ Ø¹Ù„ÙŠÙ‡ ÙˆØ³Ù„Ù…- Ø¨ÙÙŠÙŽØ¯ÙÙ‡Ù ÙˆÙŽÙ‚ÙŽØ§Ù„ÙŽ: (( Ø¨ÙØ³Ù’Ù…Ù Ø§Ù„Ù„Ù‘ÙŽÙ‡Ù ÙˆÙŽØ§Ù„Ù„Ù‘ÙŽÙ‡Ù Ø£ÙŽÙƒÙ’Ø¨ÙŽØ±Ù Ù‡ÙŽØ°ÙŽØ§ Ø¹ÙŽÙ†Ù‘ÙÙ‰ ÙˆÙŽØ¹ÙŽÙ…Ù‘ÙŽÙ†Ù’ Ù„ÙŽÙ…Ù’ ÙŠÙØ¶ÙŽØ­Ù‘Ù Ù…ÙÙ†Ù’ Ø£ÙÙ…Ù‘ÙŽØªÙÙ‰ ))', 'Artinya:â€œDiriwayatkan dari Jabir bin Abdillah radhiallahu anhu bahwasanya dia berkata, â€œSaya menghadiri shalat idul-Adha bersama Rasulullah shallallahu alaihi wa sallam di mushalla (tanah lapang). Setelah beliau berkhutbah, beliau turun dari mimbarnya dan didatangkan kepadanya seekor kambing. Kemudian Rasulullah shallallahu alaihi wa sallam menyembelihnya dengan tangannya, sambil mengatakan: Dengan nama Allah. Allah Maha Besar. Kambing ini dariku dan dari orang-orang yang belum menyembelih di kalangan umatkuâ€');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `hadits`
--
ALTER TABLE `hadits`
  ADD PRIMARY KEY (`id_hadits`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `hadits`
--
ALTER TABLE `hadits`
  MODIFY `id_hadits` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=103;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
